# 100 NumPy Exercises
Here is the reference to the original problem:https://github.com/maykulkarni/Machine-Learning-Notebooks/blob/master/00.%20NumPy%20Basics/100_Numpy_exercises_no_solution.ipynbs.

### 1. Import the numpy package under the name np

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration

In [2]:
print("Numpy version: {}".format(np.__version__))
np.show_config()

Numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/men_l/anaconda3/Library/include
    lib directory: C:/Users/men_l/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: win

### 3. Create a null vector of size 10

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array

In [4]:
a = np.zeros(10)
print("Size of one element: {}".format(a.itemsize))
print("Size of the entire array: {}". format(a.nbytes))

Size of one element: 8
Size of the entire array: 80


### 5. How to get the documentation of the numpy add function from the command line?

In [5]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------

### 6. Create a null vector of size 10 but the fifth value which is 1

In [6]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last)

In [8]:
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

### 11. Create a 3x3 identity matrix

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values

In [12]:
np.random.randint(0,100,(3,3,3))

array([[[77, 95, 26],
        [71, 84, 59],
        [46, 21, 48]],

       [[46, 98, 81],
        [44, 35, 88],
        [98, 28,  4]],

       [[21,  6, 62],
        [ 5, 90, 65],
        [53, 79, 81]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values 


In [13]:
rand_array = np.random.randint(0,100,(10,10))
print("Arr: {}".format(rand_array))
print("Min: {}".format(np.min(rand_array)))
print("Max: {}".format(np.max(rand_array)))

Arr: [[77 74 20 33 41  8 93 41 72 31]
 [87 25 10  0 37 17 25 14 96 71]
 [24  3 85 54 91 49  6 98 89 66]
 [11 40 21 72 33 74 15  3 35 62]
 [76 22 63 60 55 89 45 13 20 20]
 [65  8 78 30 48 44 57  9 53 21]
 [14 92 18 47 84 55 19 44 43 44]
 [64 82 83 35 44 15 16 86 91  5]
 [13 21 80 29 21 71  1 98 34 59]
 [84 54 82 84 55 36 23  8 83 51]]
Min: 0
Max: 98


### 14. Create a random vector of size 30 and find the mean value

In [14]:
rand_array = np.random.randint(1,30, (30))
print("Arr: {}".format(rand_array))
print("Mean: {}".format(rand_array.mean()))

Arr: [29 29  2 29 27  8 28 17  1  1  6  1 29  8  1 23  2 24 13 21 10 24 20  5
  3 20  2 11 22 16]
Mean: 14.4


### 15. Create a 2d array with 1 on the border and 0 inside 

In [15]:
# creates a 10x10 NumPy array filled with ones
arr = np.ones((10,10))
print("Before: ")
print(arr)
# arr[1:-1]: This selects rows from the second row (index 1) up to but not including the last row (index -1).
# arr[1:-1, 1:-1]: This further selects columns from the second column (index 1) up to but not including the last column (index -1).
# = 0: This assigns the value 0 to all elements within the selected range, effectively setting the inner portion of the array to zero
arr[1:-1, 1:-1] = 0 
print("\nAfter: ")
print(arr)

Before: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

After: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16 How to add a border (filled with 0's) around an existing array?

In [16]:
array = np.ones((3,3))
bordered_array  = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Original array: ")
print(array)
print("\nArray with border: ")
print(bordered_array)

Original array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with border: 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? (★☆☆)
> 0 * np.nan

> np.nan == np.nan

> np.inf > np.nan

> np.nan - np.nan

> 0.3 == 3 * 0.1

In [17]:
print(0*np.nan)
print(" ")
print(np.nan==np.nan)
print(" ")
print(np.inf>np.nan)
print(" ")
print(np.nan - np.nan)
print(" ")
print(0.3 == 3*0.1)


nan
 
False
 
False
 
nan
 
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [20]:
# Create a 5x5 matrix of zeros
matrix = np.zeros((5,5), dtype=int)
print(matrix)
print(" ")

# Assign values 1,2,3,4 just below the diagonal
for i in range(1,5):
    # matrix[i, i-1]: This part accesses the element in the matrix at the row index i and column index i-1. 
    # In a 5x5 matrix, i ranges from 0 to 4. However, in the loop, i starts from 1 to 4, so i-1 ranges from 0 to 3.
    # = i: This assigns the value of i to the element at the specified position in the matrix.
    matrix[i , i-1] = i
print(matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix  and fill it with a checkboard pattern

In [ ]:
# Create a 8x8 matrix of zero 
matrix = np.zeros((8,8), dtype = int)
print(matrix)
print(" ")
# Fill the matrix with a checkboard pattern
# This sets every other element in every other row, starting from the second row (index 1), to 1
matrix[1::2, ::2]= 1
print(matrix)
print(" ")

# This sets every other element in every other column, starting from the second column (index 1), to 1
matrix[::2, 1::2] = 1
print("This results in a checkerboard pattern where 1s and 0s alternate: ")
print(matrix)

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [30]:
# Define the shape of the array
shape = (6,7,8)
print(shape)
print(" ")

# Find the index of the 100th element (remember to subtract 1 because indexing starts at 0)
# This function takes the flat index (99, since indexing starts at 0) and the shape of the array, and returns the corresponding multi-dimensional index
index = np.unravel_index(99, shape)
print("So, the index ((x, y, z)) of the 100th element in a ((6, 7, 8)) shaped array is ((1, 5, 3))")
print(index)

(6, 7, 8)
 
So, the index ((x, y, z)) of the 100th element in a ((6, 7, 8)) shaped array is ((1, 5, 3))
(1, 5, 3)


### 21. Create a checkboard 8x8 matrix using the tile function

In [35]:
# This creates a 2x2 matrix with a checkerboard pattern
pattern = np.array([[0,1], [1,0]])
print(pattern)
print(" ")
# Tile the pattern to create an 8x8 matrix
checkerboard = np.tile(pattern, (4,4)) #This tiles the 2x2 pattern to create an 8x8 matrix by repeating the pattern 4 times along both dimensions
print(checkerboard)

[[0 1]
 [1 0]]
 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix 

In [39]:
# Create a 5x5 matrix with random values 
matrix = np.random.rand(5,5)
# Normalize the matrix
# Subtracting the minimum value from each element and then dividing by the range (max - min) normalizes the values
# This formula scales the values in the matrix to be between 0 and 1
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix)-np.min(matrix))
print("Original Matrix:\n ", matrix)
print(" ")
print("Normalized Matirx:\n ", normalized_matrix)

Original Matrix:
  [[0.21705192 0.26993045 0.14063204 0.70510004 0.49032073]
 [0.84072586 0.14856701 0.6178424  0.68931842 0.9516736 ]
 [0.74553785 0.38172631 0.7272916  0.70270022 0.51529947]
 [0.10597118 0.51755209 0.9446675  0.80486171 0.80953316]
 [0.39813819 0.96149892 0.44984648 0.43440486 0.19900162]]
 
Normalized Matirx:
  [[0.12983885 0.19164693 0.04051401 0.70030325 0.44925433]
 [0.85883209 0.04978894 0.59831049 0.6818566  0.98851548]
 [0.74756976 0.32232167 0.72624228 0.69749817 0.47845121]
 [0.         0.48108423 0.98032626 0.81691159 0.8223719 ]
 [0.34150501 1.         0.40194523 0.383896   0.10874041]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [47]:
# Define the custom dtype
color_dtype = np.dtype([
    #This defines a custom data type with four fields: ‘r’, ‘g’, ‘b’, and ‘a’, each of which is an unsigned byte (np.ubyte)
    ('r', np.ubyte), # Red channel 
    ('g', np.ubyte), # Green channel
    ('b', np.ubyte), # Blue channel
    ('a', np.ubyte)  # alpha channel
    
])
# Example of creating an array with this dtype
# This creates an array of colors using the custom dtype. Each color is represented as a tuple of four unsigned bytes
colors = np.array([(255,0,0,255), (0,255,0,255), (0,0,255,255)], dtype=color_dtype)
print(" This code output an array of colors with the specified RGBA: \n", colors)

 This code output an array of colors with the specified RGBA: 
 [(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [52]:
# Generates a 5x3 matrix with random values between 0 and 1
matrix1 = np.random.rand(5,3)
# Generates a 3x2 matrix with random values between 0 and 1
matrix2 = np.random.rand(3,2)
# Computes the dot product of the two matrices, resulting in a 5x2 matrix
result = np.dot(matrix1, matrix2)
print("First Matrix (5x3):\n", matrix1)
print(" ")
print("Second Matrix (3x2):\n", matrix2)
print(" ")
print("It will output the original matrices and their product. The resulting matrix will have the shape (5, 2):\n", result)

First Matrix (5x3):
 [[0.27531288 0.42017457 0.86409152]
 [0.27773576 0.82959562 0.72004025]
 [0.24078108 0.92095764 0.90305201]
 [0.7613535  0.19350941 0.60292403]
 [0.98574092 0.47342154 0.84619604]]
 
Second Matrix (3x2):
 [[0.25442896 0.90467457]
 [0.94540712 0.66933335]
 [0.98758561 0.72977753]]
 
It will output the original matrices and their product. The resulting matrix will have the shape (5, 2):
 [[1.32064796 1.16089998]
 [1.56607102 1.33200568]
 [1.82378276 1.49328324]
 [0.97209466 1.25829986]
 [1.53406817 1.82618642]]
