# 100 NumPy Exercises
Here is the reference to the original problem:https://github.com/maykulkarni/Machine-Learning-Notebooks/blob/master/00.%20NumPy%20Basics/100_Numpy_exercises_no_solution.ipynbs.

### 1. Import the numpy package under the name np

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration

In [2]:
print("Numpy version: {}".format(np.__version__))
np.show_config()

Numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/men_l/anaconda3/Library/include
    lib directory: C:/Users/men_l/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: win

### 3. Create a null vector of size 10

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array

In [4]:
a = np.zeros(10)
print("Size of one element: {}".format(a.itemsize))
print("Size of the entire array: {}". format(a.nbytes))

Size of one element: 8
Size of the entire array: 80


### 5. How to get the documentation of the numpy add function from the command line?

In [5]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------

### 6. Create a null vector of size 10 but the fifth value which is 1

In [6]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last)

In [8]:
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

### 11. Create a 3x3 identity matrix

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values

In [12]:
np.random.randint(0,100,(3,3,3))

array([[[10, 94, 25],
        [21, 74, 59],
        [88, 87, 81]],

       [[70, 30, 40],
        [85, 41, 54],
        [75, 32, 94]],

       [[18, 96,  4],
        [11, 20, 63],
        [ 6, 98, 32]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values 


In [13]:
rand_array = np.random.randint(0,100,(10,10))
print("Arr: {}".format(rand_array))
print("Min: {}".format(np.min(rand_array)))
print("Max: {}".format(np.max(rand_array)))

Arr: [[64 29 33  7 74 85 74 91 53  2]
 [71 84 21 29 46 99 20 48 62  0]
 [20 46 55 36  8 23 21 67 12 88]
 [43  0  8 19 86 98 42 41  6 63]
 [87 30 30 87 50 45 58 11 75 25]
 [63 45 40 81 53  7 61 76 53 14]
 [62 33 82  8 39 48 43 22 64 95]
 [23 49 57 89 74  8 69 22 48  5]
 [30 17 10 13 41 40 13 68 43 85]
 [10 68  5 57 72 57 48  4 19 48]]
Min: 0
Max: 99


### 14. Create a random vector of size 30 and find the mean value

In [14]:
rand_array = np.random.randint(1,30, (30))
print("Arr: {}".format(rand_array))
print("Mean: {}".format(rand_array.mean()))

Arr: [17  8  6  6 22  9 19  2  9  9  3 11  9 17  9 13 24 18  7  5 27 14 22  9
 27 25 24 17  1 28]
Mean: 13.9


### 15. Create a 2d array with 1 on the border and 0 inside 

In [15]:
# creates a 10x10 NumPy array filled with ones
arr = np.ones((10,10))
print("Before: ")
print(arr)
# arr[1:-1]: This selects rows from the second row (index 1) up to but not including the last row (index -1).
# arr[1:-1, 1:-1]: This further selects columns from the second column (index 1) up to but not including the last column (index -1).
# = 0: This assigns the value 0 to all elements within the selected range, effectively setting the inner portion of the array to zero
arr[1:-1, 1:-1] = 0 
print("\nAfter: ")
print(arr)

Before: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

After: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array?

In [16]:
array = np.ones((3,3))
bordered_array  = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Original array: ")
print(array)
print("\nArray with border: ")
print(bordered_array)

Original array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with border: 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? (★☆☆)
> 0 * np.nan

> np.nan == np.nan

> np.inf > np.nan

> np.nan - np.nan

> 0.3 == 3 * 0.1

In [17]:
print(0*np.nan)
print(" ")
print(np.nan==np.nan)
print(" ")
print(np.inf>np.nan)
print(" ")
print(np.nan - np.nan)
print(" ")
print(0.3 == 3*0.1)


nan
 
False
 
False
 
nan
 
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
# Create a 5x5 matrix of zeros
matrix = np.zeros((5,5), dtype=int)
print(matrix)
print(" ")

# Assign values 1,2,3,4 just below the diagonal
for i in range(1,5):
    # matrix[i, i-1]: This part accesses the element in the matrix at the row index i and column index i-1. 
    # In a 5x5 matrix, i ranges from 0 to 4. However, in the loop, i starts from 1 to 4, so i-1 ranges from 0 to 3.
    # = i: This assigns the value of i to the element at the specified position in the matrix.
    matrix[i , i-1] = i
print(matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix  and fill it with a checkboard pattern

In [19]:
# Create a 8x8 matrix of zero 
matrix = np.zeros((8,8), dtype = int)
print(matrix)
print(" ")
# Fill the matrix with a checkboard pattern
# This sets every other element in every other row, starting from the second row (index 1), to 1
matrix[1::2, ::2]= 1
print(matrix)
print(" ")

# This sets every other element in every other column, starting from the second column (index 1), to 1
matrix[::2, 1::2] = 1
print("This results in a checkerboard pattern where 1s and 0s alternate: ")
print(matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
 
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
 
This results in a checkerboard pattern where 1s and 0s alternate: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
# Define the shape of the array
shape = (6,7,8)
print(shape)
print(" ")

# Find the index of the 100th element (remember to subtract 1 because indexing starts at 0)
# This function takes the flat index (99, since indexing starts at 0) and the shape of the array, and returns the corresponding multi-dimensional index
index = np.unravel_index(99, shape)
print("So, the index ((x, y, z)) of the 100th element in a ((6, 7, 8)) shaped array is ((1, 5, 3))")
print(index)

(6, 7, 8)
 
So, the index ((x, y, z)) of the 100th element in a ((6, 7, 8)) shaped array is ((1, 5, 3))
(1, 5, 3)


### 21. Create a checkboard 8x8 matrix using the tile function

In [21]:
# This creates a 2x2 matrix with a checkerboard pattern
pattern = np.array([[0,1], [1,0]])
print(pattern)
print(" ")
# Tile the pattern to create an 8x8 matrix
checkerboard = np.tile(pattern, (4,4)) #This tiles the 2x2 pattern to create an 8x8 matrix by repeating the pattern 4 times along both dimensions
print(checkerboard)

[[0 1]
 [1 0]]
 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix 

In [22]:
# Create a 5x5 matrix with random values 
matrix = np.random.rand(5,5)
# Normalize the matrix
# Subtracting the minimum value from each element and then dividing by the range (max - min) normalizes the values
# This formula scales the values in the matrix to be between 0 and 1
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix)-np.min(matrix))
print("Original Matrix:\n ", matrix)
print(" ")
print("Normalized Matirx:\n ", normalized_matrix)

Original Matrix:
  [[0.95850721 0.97296106 0.99183028 0.82758613 0.88998155]
 [0.96927247 0.48008473 0.31195623 0.9135203  0.77784152]
 [0.57856623 0.02780299 0.055357   0.12963105 0.30651083]
 [0.07412611 0.67836032 0.17285002 0.65428868 0.86003843]
 [0.49153251 0.87607829 0.47270879 0.91736293 0.21140318]]
 
Normalized Matirx:
  [[0.96543349 0.98042667 1.         0.82962708 0.89435078]
 [0.97660045 0.46915865 0.29475643 0.91876788 0.77802625]
 [0.57131499 0.         0.02858219 0.10562778 0.28910784]
 [0.04805168 0.6748329  0.15045947 0.64986303 0.86329034]
 [0.48103361 0.87992872 0.46150748 0.9227539  0.19045125]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [23]:
# Define the custom dtype
color_dtype = np.dtype([
    #This defines a custom data type with four fields: ‘r’, ‘g’, ‘b’, and ‘a’, each of which is an unsigned byte (np.ubyte)
    ('r', np.ubyte), # Red channel 
    ('g', np.ubyte), # Green channel
    ('b', np.ubyte), # Blue channel
    ('a', np.ubyte)  # alpha channel
    
])
# Example of creating an array with this dtype
# This creates an array of colors using the custom dtype. Each color is represented as a tuple of four unsigned bytes
colors = np.array([(255,0,0,255), (0,255,0,255), (0,0,255,255)], dtype=color_dtype)
print(" This code output an array of colors with the specified RGBA: \n", colors)

 This code output an array of colors with the specified RGBA: 
 [(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [24]:
# Generates a 5x3 matrix with random values between 0 and 1
matrix1 = np.random.rand(5,3)
# Generates a 3x2 matrix with random values between 0 and 1
matrix2 = np.random.rand(3,2)
# Computes the dot product of the two matrices, resulting in a 5x2 matrix
result = np.dot(matrix1, matrix2)
print("First Matrix (5x3):\n", matrix1)
print(" ")
print("Second Matrix (3x2):\n", matrix2)
print(" ")
print("It will output the original matrices and their product. The resulting matrix will have the shape (5, 2):\n", result)

First Matrix (5x3):
 [[0.00491434 0.51483699 0.66348962]
 [0.4365022  0.44689205 0.87526532]
 [0.68514548 0.39726803 0.6444187 ]
 [0.26450807 0.37250787 0.96392637]
 [0.1069413  0.0223989  0.01672861]]
 
Second Matrix (3x2):
 [[0.83056373 0.52783403]
 [0.21290826 0.63151603]
 [0.57109657 0.80373626]]
 
It will output the original matrices and their product. The resulting matrix will have the shape (5, 2):
 [[0.49261137 0.86099243]
 [0.95755092 1.21610268]
 [1.02166394 1.1304669 ]
 [0.84949586 1.14960363]
 [0.10314412 0.08403791]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [25]:
def negate_elements_in_range(arr):
    # Converts the input list arr into a NumPy array. NumPy arrays are more efficient for numerical operations compared to Python lists
    arr = np.array(arr)
    
    # Create a boolean mask. 
    # The expression (arr >= 3) creates a boolean array where elements are True if they are greater than or equal to 3
    # (arr <= 8) creates a boolean array where elements are True if they are less than or equal to 8
    # The & operator performs an element-wise logical AND operation, combining these two conditions
    mask = (arr>=3) & (arr<= 8)
   
    # This line uses the boolean mask to select elements of arr that meet the condition (i.e., elements between 3 and 8)
    # It then negates these selected elements in place. The -arr[mask] part negates the values, 
    # and arr[mask] = ... assigns the negated values back to their original positions in the array
    arr[mask] = -arr[mask]
    return arr 
# Example Usage
arr = [1, 4, 6, 9, 3, 8, 2]
negated_arr = negate_elements_in_range(arr)
print(negated_arr)

[ 1 -4 -6  9 -3 -8  2]


### 26. What is the output of the following script? 
> print(sum(range(5),-1))

> from numpy import *

> print(sum(range(5),-1))

In [26]:
# range(5): This generates a sequence of numbers from 0 to 4 (inclusive). So, range(5) produces [0, 1, 2, 3, 4]
# The sum function calculates the sum of the elements in the sequence generated by range(5), 
# but it also takes an optional second argument, which is the starting value for the sum. In this case, the starting value is -1
# So, the calculation proceeds as follows:
# Start with -1.
# Add the elements of the sequence [0, 1, 2, 3, 4] to -1
print(sum(range(5), -1))

from numpy import * #imports all functions and classes from the NumPy library into the current namespace
# Because of the from numpy import * statement, the sum function from NumPy is used instead of the built-in Python sum function
# range(5): This generates a sequence of numbers from 0 to 4 (inclusive). So, range(5) produces [0, 1, 2, 3, 4]
# The NumPy sum function does not use the second argument as a starting value for the sum. 
# Instead, it interprets the second argument as the axis parameter, which specifies the axis along which to sum the elements
# Since -1 is not a valid axis for a 1D array, NumPy ignores it and simply sums the elements of the array [0, 1, 2, 3, 4]
# Therefore, print(sum(range(5), -1)) outputs 10 because the second argument is ignored by NumPy’s sum function in this context
print(sum(range(5),-1))

9
10


### 27. Consider an integer vector Z, which of these expressions are legal?
> Z**Z

> 2 << Z >> 2

> Z <- Z

>1 j * Z

>Z/1/1

> Z < Z > Z  

1. `Z**Z`:
   
   &bull; This expression attempts to raise each element of `Z` to the power of the corresponding element in `Z`. This is legal in Numpy.

   &bull; `Legal` 
2. `2 << Z >> 2`:

    &bull; This expression involves bitwise left and right shifts. `2 << Z` shifts the number 2 to the left by each element in `Z`, and then `>> 2` shifts the result to the right by 2. This is legal in Numpy.

   &bull; `Legal`

3. `Z <- Z`:

   &bull; This expression is not valid in Python. The `<-` operator is not defined in Python.

   &bull; `Illegal`

4. `1j*Z`:

   &bull; This expression multiplies each element of `Z` by the imaginary until `1j`. This is legal in Numpy and results in a complex array.

   &bull; `Legal`

5. `Z/1/1`:

   &bull; This expression divides each element of `Z` by 1 twice. This is legal in Numpy.

   &bull; `Legal`

6. `Z<Z>Z`:

   &bull; This expression is not valid in Python. Chained comparisons like this are not supported.

   &bull; `Illegal`.
   
   
   


### 28. What are the result of the following expressions?
> np.array(0) / np.array(0)

> np.array(0) // np.array(0)

> np.array([np.nan]).astype(int).astype(float) 

In [27]:
# This expression attempts to divide zero by zero.
# In NumPy, this results in a division by zero, which produces a NaN (Not a Number) and raises a runtime warning
np.array(0) / np.array(0)



C:\Users\men_l\AppData\Local\Temp\ipykernel_15860\164202812.py:3: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [28]:
# This expression attempts to perform integer division of zero by zero. 
# In NumPy, this also results in a division by zero, which produces 0 and raises a runtime warning
np.array(0) // np.array(0)



C:\Users\men_l\AppData\Local\Temp\ipykernel_15860\1784414740.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [29]:
# This expression first creates a NumPy array containing NaN.
# It then attempts to cast this array to an integer type. Converting NaN to an integer is not well-defined and typically results in an undefined value,
# often -9223372036854775808 (the minimum value for a 64-bit integer).
# Finally, it casts the integer array back to a float
np.array([np.nan]).astype(int).astype(float)

C:\Users\men_l\AppData\Local\Temp\ipykernel_15860\3233124507.py:5: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

### 29. How to round away from zero a float array?

In [30]:
def round_away_from_zero(arr):
    # np.abs(arr): Takes the absolute value of each element in the array
    # np.ceil(np.abs(arr)): Rounds each element up to the nearest integer
    # np.copysign(np.ceil(np.abs(arr)), arr): Applies the sign of the original elements to the rounded values, effectively rounding away from zero
    return np.copysign(np.ceil(np.abs(arr)),arr)

# Expmaple usage:
arr = np.array([-1.5, -0.2, 0.2, 1.5, 2.3, -2.3])
rounded_arr = round_away_from_zero(arr)
print(rounded_arr)

[-2. -1.  1.  2.  3. -3.]


### 30. How to find common values between two arrays?

In [31]:
array1  = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)
print(common_values)

[3 4 5]


### 31. How to ignore all numpy warnings(not recommended)?

In [32]:
# Ignore all warnings
np.seterr(all='ignore')

# Example usage
arr = np.array([1,2,3])
print(arr/0) # This will not raise a warning

[inf inf inf]


### 32. Is the following expressions true?
np.sqrt(-1) = np.emath.sqrt(-1)

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)


False

### 33. How to get the dates of yesterday, today and tomorrow?

In [34]:
# Today's date
today= np.datetime64('today', 'D')
print("Today:", today)
# Yesterday's date
yesterday = today - np.timedelta64(1, 'D')
print("Yesterday: ", yesterday)
# Tomorrow's date
tomorrow = today + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Today: 2024-10-02
Yesterday:  2024-10-01
Tomorrow:  2024-10-03


### 34. How to get all the dates corresponding to the month of July 2016?

In [35]:
# Define the state and end dates for July 2016
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

# Generate an array of all dates in July 2016
july_dates = np.arange(start_date, end_date, dtype='datetime64[D]')
print(july_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [36]:
# Example arrays
A = np.array([1,2,3,4], dtype = float)
B = np.array([5,6,7,8], dtype = float)

# Step 1: Add A and B, store the result A (in-place)
A += B
# step 2: Multiply A by -0.5 (equivalent to -A/2), store the result in A (in-place)
A *= -0.5
print(A)

[-3. -4. -5. -6.]


### 36. Extract the integer part of a random array using 5 different methods

In [37]:
# Generate a random array
random_array = np.random.random(5) * 10
print("Original array: ", random_array)

# Extract integer part using np.floor
integer_part_floor = np.floor(random_array) # Rounds down to the nearest integer
print("Integer part (floor):", integer_part_floor)

# Extract integer part using np.trunc
integer_part_trunc = np.trunc(random_array) #Truncates the decimal part, effectively rounding towards zero
print("Integer part (trunc):", integer_part_trunc)

# Extract integer part by converting to int
integer_part_int = random_array.astype(int) #Converts the array elements to integers, truncating the decimal part.
print("Integer part (astype):", integer_part_int)

# Extract integer part using np.fix
integer_part_fix = np.fix(random_array) #Rounds toward zero, similar to np.trunc.
print("Integer part (fix):", integer_part_fix)

# Extract integer part using np.vectorize with int
integer_part_vectorize = np.vectorize(int)(random_array) #Applies to int function element-wise to the array.
print("Integer part (vectorize):", integer_part_vectorize)

Original array:  [7.70686168 3.42386125 6.50836362 9.88430376 3.44950951]
Integer part (floor): [7. 3. 6. 9. 3.]
Integer part (trunc): [7. 3. 6. 9. 3.]
Integer part (astype): [7 3 6 9 3]
Integer part (fix): [7. 3. 6. 9. 3.]
Integer part (vectorize): [7 3 6 9 3]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4


In [38]:
# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.zeros((5,5))
print(matrix)
# This generates an array with values [0, 1, 2, 3, 4]. Then, it adds the array [0, 1, 2, 3, 4] to each row of the matrix
matrix += np.arange(5)
print(" ")
print(matrix)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
 
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38. Consider a generator function that generates 10 integers and use it to build an array

In [39]:
def generate_integers():
    for i in range(10):
        # First Call: When the generator is first called, it starts executing the function until it hits the yield statement. 
        #     It returns the value of i and pauses.
        # Subsequent Calls: Each subsequent call to the generator resumes execution right after the yield statement, 
        #     continues until it hits the next yield, and pauses again.
        yield i
# Create the generator
generator = generate_integers()

# Build the Numpy array from the generator
# np.fromiter: This function constructs a 1-D array from an iterable (in this case, the generator).
# The dtype parameter specifies the desired data type of the array elements
array_from_generator = np.fromiter(generator, dtype=int) #
print(array_from_generator)

[0 1 2 3 4 5 6 7 8 9]


### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [40]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.linspace(0, 1, 12, endpoint= True)[1:-1]
# np.linspace(0, 1, 12, endpoint=True): This generates 12 evenly spaced values between 0 and 1, inclusive.
# [1:-1]: This slices the array to exclude the first and last elements, resulting in 10 values between 0 and 1.
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40. Create a random vector of size 10 and sort it

In [41]:
# Create a random vector of size 10
random_vector = np.random.random(10)
print("Original:", random_vector)
print(" ")
# Sort the array
random_vector.sort()
print("Sorted array:", random_vector)

Original: [0.26657339 0.20865263 0.22396129 0.41678566 0.71190639 0.08820712
 0.88727345 0.54629146 0.07583701 0.16726634]
 
Sorted array: [0.07583701 0.08820712 0.16726634 0.20865263 0.22396129 0.26657339
 0.41678566 0.54629146 0.71190639 0.88727345]


### 41. How to sum a small array faser than np.sum?

In [42]:
# Using Python's buil-in sum function
array = np.array([1, 2, 3, 4, 5])
result = sum(array)
print(result)

# Using np.eisum
# This function is highly optimized for various operations, including summation, and can be faster for certain array types
result = np.einsum('i->', array)
print(result)

# Using np.add.reduce
# This is another NumPy function that can be faster than np.sum for small arrays due to reduced overhead.
result = np.add.reduce(array)
print(result)

15
15
15


### 42. Consider two random array A and B, check if they are equal

In [43]:
# To check if two random arrays A and B are equal, you can use NumPy's array_equal function.
# The function compares two arrays element-wise and return True if they are exactly the same, and False otherwise.
A = np.random.rand(5) 
B = np.random.rand(5) 

# Check if they are equal
are_equal = np.array_equal(A, B)
print("Array A:", A)
print("Array B:", B)
print("Are the arrays equal?", are_equal)


Array A: [0.88549179 0.3300361  0.52830926 0.60766112 0.59759289]
Array B: [0.20385185 0.89307899 0.10485691 0.91077548 0.29034963]
Are the arrays equal? False


### 43. Make an array immutable (read-only)

In [44]:
# To make a Numpy array immutable (read-only), you can set it writable flag to False
# Create a sample array
array = np.array([1, 2, 3, 4, 5])
# Make the array imutable
array.flags.writeable = False 
# Trying to modify the array will now raise an error
try:
    array[0] = 10 
except ValueError as e:
    print("Error:", e)

Error: assignment destination is read-only


### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [45]:
# Generate a random 10x2 matrix representing Cartesian cooridates
cartesian_coords = np.random.rand(10,2) 
print(cartesian_coords)
# Separate the x and y coordinates 
X = cartesian_coords[:,0]
y = cartesian_coords[:,1]

# Convert to polar coordinates
r = np.sqrt(X**2 + y**2)
theta = np. arctan2(y,X)
print(" ")
print(r)
print(" ")
print(theta)

# Combine r and theta into a single array
polar_coords = np.column_stack((r, theta))
print(" ")
print("Cartesian coordinates:\n", cartesian_coords)
print(" ")
print("Polar coordinates:\n", polar_coords)

[[3.08711319e-01 7.81960845e-02]
 [7.69975356e-01 2.37448421e-01]
 [1.74570312e-01 2.95902973e-01]
 [3.41137282e-04 4.10004432e-01]
 [5.04411678e-01 7.66502650e-02]
 [8.99487617e-01 4.50726136e-01]
 [3.71843221e-01 9.45516403e-01]
 [9.39879692e-01 6.69712103e-01]
 [2.51053707e-01 1.72213274e-01]
 [5.96590518e-01 6.69421815e-01]]
 
[0.31846084 0.80575666 0.34355984 0.41000457 0.51020232 1.00609742
 1.01600623 1.15407458 0.30444273 0.89668602]
 
[0.24808063 0.29913108 1.03779341 1.56996429 0.15080601 0.4645209
 1.19610512 0.6190998  0.60124215 0.84286294]
 
Cartesian coordinates:
 [[3.08711319e-01 7.81960845e-02]
 [7.69975356e-01 2.37448421e-01]
 [1.74570312e-01 2.95902973e-01]
 [3.41137282e-04 4.10004432e-01]
 [5.04411678e-01 7.66502650e-02]
 [8.99487617e-01 4.50726136e-01]
 [3.71843221e-01 9.45516403e-01]
 [9.39879692e-01 6.69712103e-01]
 [2.51053707e-01 1.72213274e-01]
 [5.96590518e-01 6.69421815e-01]]
 
Polar coordinates:
 [[0.31846084 0.24808063]
 [0.80575666 0.29913108]
 [0.3435598

### 45. Create a random vector of size 10 and replace the maximum value by 0

In [46]:
# Create a random vector of size 10
vector = np.random.rand(10)
print("vector:\n", vector)

# Find the index of the maximum value 
max_index = vector.argmax()
print(" ")
print("max_index:\n", max_index)

# Replace the maximum value with 0
vector[max_index] = 0 
print(" ")
print("Modified vector:\n", vector)

vector:
 [0.34394082 0.40173635 0.68193234 0.79890164 0.49341347 0.48647067
 0.38760409 0.61760545 0.75541262 0.1441461 ]
 
max_index:
 3
 
Modified vector:
 [0.34394082 0.40173635 0.68193234 0.         0.49341347 0.48647067
 0.38760409 0.61760545 0.75541262 0.1441461 ]


### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [47]:
# To create a structured array with (x) and (y) coordinates covering the ([0,1] x [0,1]) 
# area, we can use Numpy's meshgrid function along with a structured array
# Define the grid size
grid_size = 10 

# Create a structured array with 'x' and 'y'
structured_array = np.zeros((grid_size, grid_size), dtype=[('x', float), ('y', float) ])
print("structured_array:\n", structured_array)

# Generate the x and y coordinates
x,y = np.meshgrid(np.linspace(0,1, grid_size), np.linspace(0,1, grid_size))

# Assign the coordinates to the structured array
structured_array['x'], structured_array['y'] = x, y 
print(" ")
print("Structured array with x and y coordinates:\n ", structured_array)



structured_array:
 [[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]
 
Structured array with x and 

### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1(/Xi-Yj))

In [48]:
# Example arrays
x = np.array([1,2,3])
y = np.array([4,5,6])

# Constructing the Cauchy matrix
C = 1.0/(x[:, np.newaxis]- y)
# X[:, np.newaxis] reshapes X to a column vector
# The subtraction X[:, np.newaxis] - Y creates a matrix where each element is the difference between elements of X and Y
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


### 48. Print the minimum and maximum representable value for each numpy scalar type

In [49]:
import numpy as np

# np.sctypes: This attribute of the NumPy module returns a sequence containing all scalar data types supported by NumPy. 
# These data types include integers, floating-point numbers, complex numbers, booleans, and more.
for dtype in np.sctypes:

    #  Directly check if the dtype name starts with characters representing integer types. 
    # This works because standard integer type names in NumPy usually begin with 'i', 'u', or 'b' (signed integer, unsigned integer, and boolean)
  if str(dtype)[0] in ('i', 'u', 'b'):  
    print(f"dtype: {dtype}")
    print(f"Minimum value: {np.iinfo(dtype).min}")
    print(f"Maximum value: {np.iinfo(dtype).max}")
    print()

dtype: int
Minimum value: -2147483648
Maximum value: 2147483647

dtype: uint
Minimum value: 0
Maximum value: 4294967295



### 49. How to print all the values of an array

In [50]:
arr = np.array([1,2,3,4,5])
# 1. Using print() directly
print(arr)
print()
# 2. Using np.array2string()
print(np.array2string(arr))
print()
# 3. Using a loop
for value in arr:
    print(value)

[1 2 3 4 5]

[1 2 3 4 5]

1
2
3
4
5


### 50. How to find the closest value (to a given scalar) in a vector

In [51]:
# Example array and scalar
arr = np.array([1,3,8,10,15])
scalar = 9 

# Calculate the absolute differences
differences = np.abs(arr - scalar)
print("differences:\n", differences)

# Find the index of the minimum difference
index_of_min = np.argmin(differences)
print()
print("index_of_min:\n", index_of_min)

# Get the closest value
closest_value = arr[index_of_min]
print()
print(f"The closet value to {scalar} is {closest_value}")

differences:
 [8 6 1 1 6]

index_of_min:
 2

The closet value to 9 is 8


### 51. Create a structured array representing a position (x,y) and a color (r,g,b) 

In [52]:
"""To create a structured array in Numpy that represents a position (x,y) and a color (r,g,b), 
we can define a custom data type and then create the array using  that data type."""
# Define the data type with fields for position and color
# Define a structured data type with two fields: position (containing x and y coordinates) and color (containing r, g, and b values)
dtype = np.dtype([
    ('position', [('x', np.float32), ('y', np.float32)]),
    ('color', [('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])
])
# Create a structured array with the defined data type
data = np.array([
    ((1.0,2.0), (255,0,0)),
    ((3.0,4.0), (0,255,0)),
    ((5.0, 6.0), (0,0,255))
], dtype=dtype)

# Accessing the data
print(data)
print("First position:", data['position'][0])
print("First color:", data['color'][0])

[((1., 2.), (255,   0,   0)) ((3., 4.), (  0, 255,   0))
 ((5., 6.), (  0,   0, 255))]
First position: (1., 2.)
First color: (255, 0, 0)


### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [55]:
# Generate a random vector with shape (100,2)
coordinates = np.random.rand(100,2)

# Calculate the pairwise distances
    # coordinates[:, np.newaxis] adds a new axis to coordinates, changing its shape from (100, 2) to (100, 1, 2). 
        # This effectively turns each 2D coordinate into a 1x2 array, allowing for broadcasting in the next step
    # coordinates[:, np.newaxis] - coordinates:
        # Here, we subtract the original coordinates array (shape (100, 2)) from the expanded coordinates array (shape (100, 1, 2)).
        # Due to broadcasting, this operation results in an array of shape (100, 100, 2), 
        # where each element (i, j) is the difference between the i-th and j-th coordinates
    # np.linalg.norm(..., axis=2):
        # np.linalg.norm computes the Euclidean norm (or distance) along the specified axis.
        # By setting axis=2, we calculate the norm along the last axis of the (100, 100, 2) array, which corresponds to the 2D differences between points.
        # This results in a (100, 100) array where each element (i, j) represents the Euclidean distance between the i-th and j-th points
distances = np.linalg.norm(coordinates[:, np.newaxis] - coordinates, axis=2)

print(distances)

[[0.         0.89419428 0.68236481 ... 0.97908997 0.24584964 1.03998651]
 [0.89419428 0.         0.52956418 ... 0.18453043 1.07836311 0.40249318]
 [0.68236481 0.52956418 0.         ... 0.47418766 0.75425257 0.41068805]
 ...
 [0.97908997 0.18453043 0.47418766 ... 0.         1.13344184 0.22609413]
 [0.24584964 1.07836311 0.75425257 ... 1.13344184 0.         1.15156887]
 [1.03998651 0.40249318 0.41068805 ... 0.22609413 1.15156887 0.        ]]


### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

To convert a float (32) array into an array (32 bits) array in place using Numpy, we can use the `astype` method. However, 
note that `astype` does not modify the array in place; it creates a new array. To achieve an in-place conversion, we can use the `view`
method to reinterpret the data type and then assign the values back.

In [59]:
# Create a float32 array
float_array = np.random.rand(10).astype(np.float32)
# Convert the float array to int32 in place
float_array[:] = float_array.view(np.int32)
print(float_array)

[1.05778323e+09 1.06186195e+09 1.06121242e+09 1.05762605e+09
 1.03706195e+09 1.05363142e+09 1.05819834e+09 1.06060947e+09
 1.02427686e+09 1.05302291e+09]


### 54. How to read the following file? 
>1, 2, 3, 4, 5

>6,  ,  , 7, 8

>,  , 9,10,11 

To read a file with missing values, we can use the pandas.read_csv function, which handles missing values gracefully. 

In [71]:
# Create a sample file with the given data 
with open('sample.csv', 'w') as file:
        file.write("1, 2, 3, 4, 5\n")
        file.write("6,  ,  , 7, 8\n")
        file.write(" ,  , 9,10,11\n")
# Read the the file into a DataFrame
df = pd.read_csv('sample.csv', header= None, skipinitialspace= True)
# header=None indicates that the file does not have a header row
# skipinitialspace=True ensures that any spaces after the commas are ignored 

print(df)

     0    1    2   3   4
0  1.0  2.0  3.0   4   5
1  6.0  NaN  NaN   7   8
2  NaN  NaN  9.0  10  11


### 55. What is the equivalent of enumerate for numpy arrays?

The equivalent of `enumerate` for Numpy arrays is `np.ndenumerate`. This
function allows you to iterate over a Numpy array while getting both the index and the value of each element.

In [74]:
# Example with a 1D array
arr = np.array([10,20,30,40])
for index, value in np.ndenumerate(arr):
    print(index, value)
print()
# Example with a 2D array
arr = np.array([[1,2], [3,4]])
for index, value in np.ndenumerate(arr):
    print(index, value)
    

(0,) 10
(1,) 20
(2,) 30
(3,) 40

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
