# 100 NumPy Exercises
Here is the reference to the original problem:https://github.com/maykulkarni/Machine-Learning-Notebooks/blob/master/00.%20NumPy%20Basics/100_Numpy_exercises_no_solution.ipynbs.

### 1. Import the numpy package under the name np

In [2]:
import numpy as np

### 2. Print the numpy version and the configuration

In [3]:
print("Numpy version: {}".format(np.__version__))
np.show_config()

Numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/men_l/anaconda3/Library/include
    lib directory: C:/Users/men_l/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: win

### 3. Create a null vector of size 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array

In [5]:
a = np.zeros(10)
print("Size of one element: {}".format(a.itemsize))
print("Size of the entire array: {}". format(a.nbytes))

Size of one element: 8
Size of the entire array: 80


### 5. How to get the documentation of the numpy add function from the command line?

In [6]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------

### 6. Create a null vector of size 10 but the fifth value which is 1

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last)

In [9]:
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

### 11. Create a 3x3 identity matrix

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values

In [13]:
np.random.randint(0,100,(3,3,3))

array([[[56, 83, 14],
        [26, 98, 41],
        [14, 13, 30]],

       [[96, 45, 52],
        [84, 11, 65],
        [41, 34, 88]],

       [[70, 47, 69],
        [35, 85, 42],
        [74,  8,  9]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values 


In [14]:
rand_array = np.random.randint(0,100,(10,10))
print("Arr: {}".format(rand_array))
print("Min: {}".format(np.min(rand_array)))
print("Max: {}".format(np.max(rand_array)))

Arr: [[15 84 19 90 64 34 56 74 58 36]
 [ 9 26 20 74 34 70 93 60 84  1]
 [88 82 94 62 37  7 31 17 37 38]
 [23 26 37 45 72 61 47  7 86 94]
 [17 54 84 66 57 86 57 37 93 55]
 [97 25 60 11 62 18 78 78  8 50]
 [20 53 91 48 68 74 49 87 35 96]
 [71 46 14  4 23 98 52  0 23 63]
 [45 98 55 85 39 53  2 72 94 62]
 [35 52 26 89 95 86 97 65 52 99]]
Min: 0
Max: 99


### 14. Create a random vector of size 30 and find the mean value

In [15]:
rand_array = np.random.randint(1,30, (30))
print("Arr: {}".format(rand_array))
print("Mean: {}".format(rand_array.mean()))

Arr: [ 4 26 15 12  4 16 21 20 11 26 12 29 21 15  8 13 29 15 28 16 20 14 13  1
  3 13 26 12 22 19]
Mean: 16.133333333333333


### 15. Create a 2d array with 1 on the border and 0 inside 

In [16]:
# creates a 10x10 NumPy array filled with ones
arr = np.ones((10,10))
print("Before: ")
print(arr)
# arr[1:-1]: This selects rows from the second row (index 1) up to but not including the last row (index -1).
# arr[1:-1, 1:-1]: This further selects columns from the second column (index 1) up to but not including the last column (index -1).
# = 0: This assigns the value 0 to all elements within the selected range, effectively setting the inner portion of the array to zero
arr[1:-1, 1:-1] = 0 
print("\nAfter: ")
print(arr)

Before: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

After: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16 How to add a border (filled with 0's) around an existing array?

In [17]:
array = np.ones((3,3))
bordered_array  = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Original array: ")
print(array)
print("\nArray with border: ")
print(bordered_array)

Original array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with border: 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? (★☆☆)
> 0 * np.nan

> np.nan == np.nan

> np.inf > np.nan

> np.nan - np.nan

> 0.3 == 3 * 0.1

In [18]:
print(0*np.nan)
print(" ")
print(np.nan==np.nan)
print(" ")
print(np.inf>np.nan)
print(" ")
print(np.nan - np.nan)
print(" ")
print(0.3 == 3*0.1)


nan
 
False
 
False
 
nan
 
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [19]:
# Create a 5x5 matrix of zeros
matrix = np.zeros((5,5), dtype=int)
print(matrix)
print(" ")

# Assign values 1,2,3,4 just below the diagonal
for i in range(1,5):
    # matrix[i, i-1]: This part accesses the element in the matrix at the row index i and column index i-1. 
    # In a 5x5 matrix, i ranges from 0 to 4. However, in the loop, i starts from 1 to 4, so i-1 ranges from 0 to 3.
    # = i: This assigns the value of i to the element at the specified position in the matrix.
    matrix[i , i-1] = i
print(matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix  and fill it with a checkboard pattern

In [20]:
# Create a 8x8 matrix of zero 
matrix = np.zeros((8,8), dtype = int)
print(matrix)
print(" ")
# Fill the matrix with a checkboard pattern
# This sets every other element in every other row, starting from the second row (index 1), to 1
matrix[1::2, ::2]= 1
print(matrix)
print(" ")

# This sets every other element in every other column, starting from the second column (index 1), to 1
matrix[::2, 1::2] = 1
print("This results in a checkerboard pattern where 1s and 0s alternate: ")
print(matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
 
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
 
This results in a checkerboard pattern where 1s and 0s alternate: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
# Define the shape of the array
shape = (6,7,8)
print(shape)
print(" ")

# Find the index of the 100th element (remember to subtract 1 because indexing starts at 0)
# This function takes the flat index (99, since indexing starts at 0) and the shape of the array, and returns the corresponding multi-dimensional index
index = np.unravel_index(99, shape)
print("So, the index ((x, y, z)) of the 100th element in a ((6, 7, 8)) shaped array is ((1, 5, 3))")
print(index)

(6, 7, 8)
 
So, the index ((x, y, z)) of the 100th element in a ((6, 7, 8)) shaped array is ((1, 5, 3))
(1, 5, 3)


### 21. Create a checkboard 8x8 matrix using the tile function

In [22]:
# This creates a 2x2 matrix with a checkerboard pattern
pattern = np.array([[0,1], [1,0]])
print(pattern)
print(" ")
# Tile the pattern to create an 8x8 matrix
checkerboard = np.tile(pattern, (4,4)) #This tiles the 2x2 pattern to create an 8x8 matrix by repeating the pattern 4 times along both dimensions
print(checkerboard)

[[0 1]
 [1 0]]
 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix 

In [23]:
# Create a 5x5 matrix with random values 
matrix = np.random.rand(5,5)
# Normalize the matrix
# Subtracting the minimum value from each element and then dividing by the range (max - min) normalizes the values
# This formula scales the values in the matrix to be between 0 and 1
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix)-np.min(matrix))
print("Original Matrix:\n ", matrix)
print(" ")
print("Normalized Matirx:\n ", normalized_matrix)

Original Matrix:
  [[0.23322575 0.40412773 0.22323211 0.00563043 0.42900799]
 [0.10112562 0.41140895 0.01036581 0.55201544 0.41769922]
 [0.21401926 0.43876414 0.79976371 0.80316373 0.0212414 ]
 [0.63601314 0.83493781 0.89962361 0.29285441 0.19640524]
 [0.00358336 0.32480359 0.84374291 0.38449964 0.50415925]]
 
Normalized Matirx:
  [[0.25628579 0.44701605 0.24513268 0.00228457 0.47478294]
 [0.10885923 0.45514204 0.00756935 0.61206187 0.46216211]
 [0.23485095 0.48567101 0.88855422 0.89234872 0.01970675]
 [0.7058051  0.92780926 1.         0.32283264 0.21519332]
 [0.         0.35848861 0.93763594 0.42511067 0.55865335]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [24]:
# Define the custom dtype
color_dtype = np.dtype([
    #This defines a custom data type with four fields: ‘r’, ‘g’, ‘b’, and ‘a’, each of which is an unsigned byte (np.ubyte)
    ('r', np.ubyte), # Red channel 
    ('g', np.ubyte), # Green channel
    ('b', np.ubyte), # Blue channel
    ('a', np.ubyte)  # alpha channel
    
])
# Example of creating an array with this dtype
# This creates an array of colors using the custom dtype. Each color is represented as a tuple of four unsigned bytes
colors = np.array([(255,0,0,255), (0,255,0,255), (0,0,255,255)], dtype=color_dtype)
print(" This code output an array of colors with the specified RGBA: \n", colors)

 This code output an array of colors with the specified RGBA: 
 [(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [25]:
# Generates a 5x3 matrix with random values between 0 and 1
matrix1 = np.random.rand(5,3)
# Generates a 3x2 matrix with random values between 0 and 1
matrix2 = np.random.rand(3,2)
# Computes the dot product of the two matrices, resulting in a 5x2 matrix
result = np.dot(matrix1, matrix2)
print("First Matrix (5x3):\n", matrix1)
print(" ")
print("Second Matrix (3x2):\n", matrix2)
print(" ")
print("It will output the original matrices and their product. The resulting matrix will have the shape (5, 2):\n", result)

First Matrix (5x3):
 [[0.71577698 0.49171392 0.54332842]
 [0.94699316 0.23470719 0.1246999 ]
 [0.10312364 0.01093327 0.78466955]
 [0.47520404 0.76593095 0.93091955]
 [0.56853337 0.57282039 0.20883531]]
 
Second Matrix (3x2):
 [[0.19059283 0.82869988]
 [0.93704822 0.37384651]
 [0.269073   0.551873  ]]
 
It will output the original matrices and their product. The resulting matrix will have the shape (5, 2):
 [[0.74337662 1.07683812]
 [0.43397544 0.94133609]
 [0.24103302 0.52258385]
 [1.05877003 1.19389151]
 [0.70131065 0.80054101]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [28]:
def negate_elements_in_range(arr):
    # Converts the input list arr into a NumPy array. NumPy arrays are more efficient for numerical operations compared to Python lists
    arr = np.array(arr)
    
    # Create a boolean mask. 
    # The expression (arr >= 3) creates a boolean array where elements are True if they are greater than or equal to 3
    # (arr <= 8) creates a boolean array where elements are True if they are less than or equal to 8
    # The & operator performs an element-wise logical AND operation, combining these two conditions
    mask = (arr>=3) & (arr<= 8)
   
    # This line uses the boolean mask to select elements of arr that meet the condition (i.e., elements between 3 and 8)
    # It then negates these selected elements in place. The -arr[mask] part negates the values, 
    # and arr[mask] = ... assigns the negated values back to their original positions in the array
    arr[mask] = -arr[mask]
    return arr 
# Example Usage
arr = [1, 4, 6, 9, 3, 8, 2]
negated_arr = negate_elements_in_range(arr)
print(negated_arr)

[False  True  True False  True  True False]
[ 1 -4 -6  9 -3 -8  2]


### 26. What is the output of the following script? 
> print(sum(range(5),-1))

> from numpy import *

> print(sum(range(5),-1))

In [36]:
# range(5): This generates a sequence of numbers from 0 to 4 (inclusive). So, range(5) produces [0, 1, 2, 3, 4]
# The sum function calculates the sum of the elements in the sequence generated by range(5), 
# but it also takes an optional second argument, which is the starting value for the sum. In this case, the starting value is -1
# So, the calculation proceeds as follows:
# Start with -1.
# Add the elements of the sequence [0, 1, 2, 3, 4] to -1
print(sum(range(5), -1))

from numpy import * #imports all functions and classes from the NumPy library into the current namespace
# Because of the from numpy import * statement, the sum function from NumPy is used instead of the built-in Python sum function
# range(5): This generates a sequence of numbers from 0 to 4 (inclusive). So, range(5) produces [0, 1, 2, 3, 4]
# The NumPy sum function does not use the second argument as a starting value for the sum. 
# Instead, it interprets the second argument as the axis parameter, which specifies the axis along which to sum the elements
# Since -1 is not a valid axis for a 1D array, NumPy ignores it and simply sums the elements of the array [0, 1, 2, 3, 4]
# Therefore, print(sum(range(5), -1)) outputs 10 because the second argument is ignored by NumPy’s sum function in this context
print(sum(range(5),-1))

10
10


### 27. Consider an integer vector Z, which of these expressions are legal?
> Z**Z

> 2 << Z >> 2

> Z <- Z

>1 j * Z

>Z/1/1

> Z < Z > Z  

1. `Z**Z`:
   
   &bull; This expression attempts to raise each element of `Z` to the power of the corresponding element in `Z`. This is legal in Numpy.

   &bull; `Legal` 
2. `2 << Z >> 2`:

    &bull; This expression involves bitwise left and right shifts. `2 << Z` shifts the number 2 to the left by each element in `Z`, and then `>> 2` shifts the result to the right by 2. This is legal in Numpy.

   &bull; `Legal`

3. `Z <- Z`:

   &bull; This expression is not valid in Python. The `<-` operator is not defined in Python.

   &bull; `Illegal`

4. `1j*Z`:

   &bull; This expression multiplies each element of `Z` by the imaginary until `1j`. This is legal in Numpy and results in a complex array.

   &bull; `Legal`

5. `Z/1/1`:

   &bull; This expression divides each element of `Z` by 1 twice. This is legal in Numpy.

   &bull; `Legal`

6. `Z<Z>Z`:

   &bull; This expression is not valid in Python. Chained comparisons like this are not supported.

   &bull; `Illegal`.
   
   
   


### 28. What are the result of the following expressions?
> np.array(0) / np.array(0)

> np.array(0) // np.array(0)

> np.array([np.nan]).astype(int).astype(float) 

In [49]:
# This expression attempts to divide zero by zero.
# In NumPy, this results in a division by zero, which produces a NaN (Not a Number) and raises a runtime warning
np.array(0) / np.array(0)



C:\Users\men_l\AppData\Local\Temp\ipykernel_27008\164202812.py:3: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [47]:
# This expression attempts to perform integer division of zero by zero. 
# In NumPy, this also results in a division by zero, which produces 0 and raises a runtime warning
np.array(0) // np.array(0)



C:\Users\men_l\AppData\Local\Temp\ipykernel_27008\1784414740.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [48]:
# This expression first creates a NumPy array containing NaN.
# It then attempts to cast this array to an integer type. Converting NaN to an integer is not well-defined and typically results in an undefined value,
# often -9223372036854775808 (the minimum value for a 64-bit integer).
# Finally, it casts the integer array back to a float
np.array([np.nan]).astype(int).astype(float)

C:\Users\men_l\AppData\Local\Temp\ipykernel_27008\3233124507.py:5: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

### 29. How to round away from zero a float array?

In [51]:
def round_away_from_zero(arr):
    # np.abs(arr): Takes the absolute value of each element in the array
    # np.ceil(np.abs(arr)): Rounds each element up to the nearest integer
    # np.copysign(np.ceil(np.abs(arr)), arr): Applies the sign of the original elements to the rounded values, effectively rounding away from zero
    return np.copysign(np.ceil(np.abs(arr)),arr)

# Expmaple usage:
arr = np.array([-1.5, -0.2, 0.2, 1.5, 2.3, -2.3])
rounded_arr = round_away_from_zero(arr)
print(rounded_arr)

[-2. -1.  1.  2.  3. -3.]


### 30. How to find common values between two arrays?

In [52]:
array1  = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)
print(common_values)

[3 4 5]


### How to ignore all numpy warnings(not recommended)?

In [59]:
# Ignore all warnings
np.seterr(all='ignore')

# Example usage
arr = np.array([1,2,3])
print(arr/0) # This will not raise a warning

[inf inf inf]
