# 100 NumPy Exercises
Here is the reference to the original problem:https://github.com/maykulkarni/Machine-Learning-Notebooks/blob/master/00.%20NumPy%20Basics/100_Numpy_exercises_no_solution.ipynbs.

### 1. Import the numpy package under the name np

In [2]:
import numpy as np

### 2. Print the numpy version and the configuration

In [3]:
print("Numpy version: {}".format(np.__version__))
np.show_config()

Numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/men_l/anaconda3/Library/include
    lib directory: C:/Users/men_l/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: win

### 3. Create a null vector of size 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array

In [5]:
a = np.zeros(10)
print("Size of one element: {}".format(a.itemsize))
print("Size of the entire array: {}". format(a.nbytes))

Size of one element: 8
Size of the entire array: 80


### 5. How to get the documentation of the numpy add function from the command line?

In [6]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------

### 6. Create a null vector of size 10 but the fifth value which is 1

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last)

In [9]:
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

### 11. Create a 3x3 identity matrix

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values

In [13]:
np.random.randint(0,100,(3,3,3))

array([[[66, 33, 45],
        [18, 20, 73],
        [ 8, 48, 27]],

       [[90, 42, 77],
        [31, 40, 28],
        [23, 40,  2]],

       [[ 3, 36,  7],
        [65, 38, 80],
        [11, 83, 33]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values 


In [14]:
rand_array = np.random.randint(0,100,(10,10))
print("Arr: {}".format(rand_array))
print("Min: {}".format(np.min(rand_array)))
print("Max: {}".format(np.max(rand_array)))

Arr: [[55 52 22 39 74 70 33 68 95 28]
 [16 86 22 59 76 21 28 44 24 56]
 [61 95 78 29 70 79 85 69 85 89]
 [ 7 68 49 78 14 79 21 46 65 77]
 [ 7 90 29 37 64 46 11  1 97  5]
 [33 53 71 53 15 72 23 17 79 60]
 [44 86  7 67 45 28 64 21 66  4]
 [66 31 11 38 71 49 44  8 22 45]
 [33 28  0 95  9 16 45 78 39  5]
 [55 88 57 61 40 91  1 94  6 50]]
Min: 0
Max: 97


### 14. Create a random vector of size 30 and find the mean value

In [15]:
rand_array = np.random.randint(1,30, (30))
print("Arr: {}".format(rand_array))
print("Mean: {}".format(rand_array.mean()))

Arr: [ 5 17 23  4 25 14  4  5 29 26  1 13 17 18  8  1 24 18 18 16 27 17 23  7
  6  1  2 25 22 13]
Mean: 14.3


### 15. Create a 2d array with 1 on the border and 0 inside 

In [16]:
# creates a 10x10 NumPy array filled with ones
arr = np.ones((10,10))
print("Before: ")
print(arr)
# arr[1:-1]: This selects rows from the second row (index 1) up to but not including the last row (index -1).
# arr[1:-1, 1:-1]: This further selects columns from the second column (index 1) up to but not including the last column (index -1).
# = 0: This assigns the value 0 to all elements within the selected range, effectively setting the inner portion of the array to zero
arr[1:-1, 1:-1] = 0 
print("\nAfter: ")
print(arr)

Before: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

After: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array?

In [17]:
array = np.ones((3,3))
bordered_array  = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Original array: ")
print(array)
print("\nArray with border: ")
print(bordered_array)

Original array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with border: 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? (★☆☆)
> 0 * np.nan

> np.nan == np.nan

> np.inf > np.nan

> np.nan - np.nan

> 0.3 == 3 * 0.1

In [18]:
print(0*np.nan)
print(" ")
print(np.nan==np.nan)
print(" ")
print(np.inf>np.nan)
print(" ")
print(np.nan - np.nan)
print(" ")
print(0.3 == 3*0.1)


nan
 
False
 
False
 
nan
 
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [19]:
# Create a 5x5 matrix of zeros
matrix = np.zeros((5,5), dtype=int)
print(matrix)
print(" ")

# Assign values 1,2,3,4 just below the diagonal
for i in range(1,5):
    # matrix[i, i-1]: This part accesses the element in the matrix at the row index i and column index i-1. 
    # In a 5x5 matrix, i ranges from 0 to 4. However, in the loop, i starts from 1 to 4, so i-1 ranges from 0 to 3.
    # = i: This assigns the value of i to the element at the specified position in the matrix.
    matrix[i , i-1] = i
print(matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix  and fill it with a checkboard pattern

In [20]:
# Create a 8x8 matrix of zero 
matrix = np.zeros((8,8), dtype = int)
print(matrix)
print(" ")
# Fill the matrix with a checkboard pattern
# This sets every other element in every other row, starting from the second row (index 1), to 1
matrix[1::2, ::2]= 1
print(matrix)
print(" ")

# This sets every other element in every other column, starting from the second column (index 1), to 1
matrix[::2, 1::2] = 1
print("This results in a checkerboard pattern where 1s and 0s alternate: ")
print(matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
 
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
 
This results in a checkerboard pattern where 1s and 0s alternate: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
# Define the shape of the array
shape = (6,7,8)
print(shape)
print(" ")

# Find the index of the 100th element (remember to subtract 1 because indexing starts at 0)
# This function takes the flat index (99, since indexing starts at 0) and the shape of the array, and returns the corresponding multi-dimensional index
index = np.unravel_index(99, shape)
print("So, the index ((x, y, z)) of the 100th element in a ((6, 7, 8)) shaped array is ((1, 5, 3))")
print(index)

(6, 7, 8)
 
So, the index ((x, y, z)) of the 100th element in a ((6, 7, 8)) shaped array is ((1, 5, 3))
(1, 5, 3)


### 21. Create a checkboard 8x8 matrix using the tile function

In [22]:
# This creates a 2x2 matrix with a checkerboard pattern
pattern = np.array([[0,1], [1,0]])
print(pattern)
print(" ")
# Tile the pattern to create an 8x8 matrix
checkerboard = np.tile(pattern, (4,4)) #This tiles the 2x2 pattern to create an 8x8 matrix by repeating the pattern 4 times along both dimensions
print(checkerboard)

[[0 1]
 [1 0]]
 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix 

In [23]:
# Create a 5x5 matrix with random values 
matrix = np.random.rand(5,5)
# Normalize the matrix
# Subtracting the minimum value from each element and then dividing by the range (max - min) normalizes the values
# This formula scales the values in the matrix to be between 0 and 1
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix)-np.min(matrix))
print("Original Matrix:\n ", matrix)
print(" ")
print("Normalized Matirx:\n ", normalized_matrix)

Original Matrix:
  [[0.99232971 0.77697877 0.94788123 0.57162074 0.42000966]
 [0.29999786 0.44468917 0.66858167 0.06136147 0.46680827]
 [0.81428679 0.18692073 0.61422991 0.13446488 0.59733585]
 [0.23782352 0.5474167  0.67266842 0.95618296 0.15586452]
 [0.75443547 0.05918704 0.16338114 0.38891654 0.3574058 ]]
 
Normalized Matirx:
  [[1.         0.7692197  0.9523669  0.54914829 0.38667465]
 [0.25806431 0.4131224  0.65305623 0.00233023 0.43682627]
 [0.80920075 0.13688548 0.5948103  0.08067131 0.57670582]
 [0.19143533 0.52321009 0.65743578 0.96126342 0.10360418]
 [0.74506124 0.         0.11165934 0.35335379 0.31958539]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [24]:
# Define the custom dtype
color_dtype = np.dtype([
    #This defines a custom data type with four fields: ‘r’, ‘g’, ‘b’, and ‘a’, each of which is an unsigned byte (np.ubyte)
    ('r', np.ubyte), # Red channel 
    ('g', np.ubyte), # Green channel
    ('b', np.ubyte), # Blue channel
    ('a', np.ubyte)  # alpha channel
    
])
# Example of creating an array with this dtype
# This creates an array of colors using the custom dtype. Each color is represented as a tuple of four unsigned bytes
colors = np.array([(255,0,0,255), (0,255,0,255), (0,0,255,255)], dtype=color_dtype)
print(" This code output an array of colors with the specified RGBA: \n", colors)

 This code output an array of colors with the specified RGBA: 
 [(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [25]:
# Generates a 5x3 matrix with random values between 0 and 1
matrix1 = np.random.rand(5,3)
# Generates a 3x2 matrix with random values between 0 and 1
matrix2 = np.random.rand(3,2)
# Computes the dot product of the two matrices, resulting in a 5x2 matrix
result = np.dot(matrix1, matrix2)
print("First Matrix (5x3):\n", matrix1)
print(" ")
print("Second Matrix (3x2):\n", matrix2)
print(" ")
print("It will output the original matrices and their product. The resulting matrix will have the shape (5, 2):\n", result)

First Matrix (5x3):
 [[0.0565401  0.6672929  0.15865474]
 [0.93351248 0.40450534 0.05128673]
 [0.96235381 0.19756179 0.51362803]
 [0.13720292 0.99656968 0.21491855]
 [0.96571981 0.01664741 0.89716498]]
 
Second Matrix (3x2):
 [[0.17828541 0.10853543]
 [0.7839109  0.7882623 ]
 [0.82059129 0.78924767]]
 
It will output the original matrices and their product. The resulting matrix will have the shape (5, 2):
 [[0.66336915 0.65735632]
 [0.52561325 0.46065342]
 [0.74792317 0.66555971]
 [0.9820434  0.97007364]
 [0.92142961 0.82602271]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [26]:
def negate_elements_in_range(arr):
    # Converts the input list arr into a NumPy array. NumPy arrays are more efficient for numerical operations compared to Python lists
    arr = np.array(arr)
    
    # Create a boolean mask. 
    # The expression (arr >= 3) creates a boolean array where elements are True if they are greater than or equal to 3
    # (arr <= 8) creates a boolean array where elements are True if they are less than or equal to 8
    # The & operator performs an element-wise logical AND operation, combining these two conditions
    mask = (arr>=3) & (arr<= 8)
   
    # This line uses the boolean mask to select elements of arr that meet the condition (i.e., elements between 3 and 8)
    # It then negates these selected elements in place. The -arr[mask] part negates the values, 
    # and arr[mask] = ... assigns the negated values back to their original positions in the array
    arr[mask] = -arr[mask]
    return arr 
# Example Usage
arr = [1, 4, 6, 9, 3, 8, 2]
negated_arr = negate_elements_in_range(arr)
print(negated_arr)

[ 1 -4 -6  9 -3 -8  2]


### 26. What is the output of the following script? 
> print(sum(range(5),-1))

> from numpy import *

> print(sum(range(5),-1))

In [27]:
# range(5): This generates a sequence of numbers from 0 to 4 (inclusive). So, range(5) produces [0, 1, 2, 3, 4]
# The sum function calculates the sum of the elements in the sequence generated by range(5), 
# but it also takes an optional second argument, which is the starting value for the sum. In this case, the starting value is -1
# So, the calculation proceeds as follows:
# Start with -1.
# Add the elements of the sequence [0, 1, 2, 3, 4] to -1
print(sum(range(5), -1))

from numpy import * #imports all functions and classes from the NumPy library into the current namespace
# Because of the from numpy import * statement, the sum function from NumPy is used instead of the built-in Python sum function
# range(5): This generates a sequence of numbers from 0 to 4 (inclusive). So, range(5) produces [0, 1, 2, 3, 4]
# The NumPy sum function does not use the second argument as a starting value for the sum. 
# Instead, it interprets the second argument as the axis parameter, which specifies the axis along which to sum the elements
# Since -1 is not a valid axis for a 1D array, NumPy ignores it and simply sums the elements of the array [0, 1, 2, 3, 4]
# Therefore, print(sum(range(5), -1)) outputs 10 because the second argument is ignored by NumPy’s sum function in this context
print(sum(range(5),-1))

9
10


### 27. Consider an integer vector Z, which of these expressions are legal?
> Z**Z

> 2 << Z >> 2

> Z <- Z

>1 j * Z

>Z/1/1

> Z < Z > Z  

1. `Z**Z`:
   
   &bull; This expression attempts to raise each element of `Z` to the power of the corresponding element in `Z`. This is legal in Numpy.

   &bull; `Legal` 
2. `2 << Z >> 2`:

    &bull; This expression involves bitwise left and right shifts. `2 << Z` shifts the number 2 to the left by each element in `Z`, and then `>> 2` shifts the result to the right by 2. This is legal in Numpy.

   &bull; `Legal`

3. `Z <- Z`:

   &bull; This expression is not valid in Python. The `<-` operator is not defined in Python.

   &bull; `Illegal`

4. `1j*Z`:

   &bull; This expression multiplies each element of `Z` by the imaginary until `1j`. This is legal in Numpy and results in a complex array.

   &bull; `Legal`

5. `Z/1/1`:

   &bull; This expression divides each element of `Z` by 1 twice. This is legal in Numpy.

   &bull; `Legal`

6. `Z<Z>Z`:

   &bull; This expression is not valid in Python. Chained comparisons like this are not supported.

   &bull; `Illegal`.
   
   
   


### 28. What are the result of the following expressions?
> np.array(0) / np.array(0)

> np.array(0) // np.array(0)

> np.array([np.nan]).astype(int).astype(float) 

In [28]:
# This expression attempts to divide zero by zero.
# In NumPy, this results in a division by zero, which produces a NaN (Not a Number) and raises a runtime warning
np.array(0) / np.array(0)



C:\Users\men_l\AppData\Local\Temp\ipykernel_22508\164202812.py:3: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [29]:
# This expression attempts to perform integer division of zero by zero. 
# In NumPy, this also results in a division by zero, which produces 0 and raises a runtime warning
np.array(0) // np.array(0)



C:\Users\men_l\AppData\Local\Temp\ipykernel_22508\1784414740.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [30]:
# This expression first creates a NumPy array containing NaN.
# It then attempts to cast this array to an integer type. Converting NaN to an integer is not well-defined and typically results in an undefined value,
# often -9223372036854775808 (the minimum value for a 64-bit integer).
# Finally, it casts the integer array back to a float
np.array([np.nan]).astype(int).astype(float)

C:\Users\men_l\AppData\Local\Temp\ipykernel_22508\3233124507.py:5: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

### 29. How to round away from zero a float array?

In [31]:
def round_away_from_zero(arr):
    # np.abs(arr): Takes the absolute value of each element in the array
    # np.ceil(np.abs(arr)): Rounds each element up to the nearest integer
    # np.copysign(np.ceil(np.abs(arr)), arr): Applies the sign of the original elements to the rounded values, effectively rounding away from zero
    return np.copysign(np.ceil(np.abs(arr)),arr)

# Expmaple usage:
arr = np.array([-1.5, -0.2, 0.2, 1.5, 2.3, -2.3])
rounded_arr = round_away_from_zero(arr)
print(rounded_arr)

[-2. -1.  1.  2.  3. -3.]


### 30. How to find common values between two arrays?

In [32]:
array1  = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)
print(common_values)

[3 4 5]


### 31. How to ignore all numpy warnings(not recommended)?

In [33]:
# Ignore all warnings
np.seterr(all='ignore')

# Example usage
arr = np.array([1,2,3])
print(arr/0) # This will not raise a warning

[inf inf inf]


### 32. Is the following expressions true?
np.sqrt(-1) = np.emath.sqrt(-1)

In [34]:
np.sqrt(-1) == np.emath.sqrt(-1)


False

### 33. How to get the dates of yesterday, today and tomorrow?

In [35]:
# Today's date
today= np.datetime64('today', 'D')
print("Today:", today)
# Yesterday's date
yesterday = today - np.timedelta64(1, 'D')
print("Yesterday: ", yesterday)
# Tomorrow's date
tomorrow = today + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Today: 2024-09-30
Yesterday:  2024-09-29
Tomorrow:  2024-10-01


### 34. How to get all the dates corresponding to the month of July 2016?

In [36]:
# Define the state and end dates for July 2016
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

# Generate an array of all dates in July 2016
july_dates = np.arange(start_date, end_date, dtype='datetime64[D]')
print(july_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [37]:
# Example arrays
A = np.array([1,2,3,4], dtype = float)
B = np.array([5,6,7,8], dtype = float)

# Step 1: Add A and B, store the result A (in-place)
A += B
# step 2: Multiply A by -0.5 (equivalent to -A/2), store the result in A (in-place)
A *= -0.5
print(A)

[-3. -4. -5. -6.]


### 36. Extract the integer part of a random array using 5 different methods

In [38]:
# Generate a random array
random_array = np.random.random(5) * 10
print("Original array: ", random_array)

# Extract integer part using np.floor
integer_part_floor = np.floor(random_array) # Rounds down to the nearest integer
print("Integer part (floor):", integer_part_floor)

# Extract integer part using np.trunc
integer_part_trunc = np.trunc(random_array) #Truncates the decimal part, effectively rounding towards zero
print("Integer part (trunc):", integer_part_trunc)

# Extract integer part by converting to int
integer_part_int = random_array.astype(int) #Converts the array elements to integers, truncating the decimal part.
print("Integer part (astype):", integer_part_int)

# Extract integer part using np.fix
integer_part_fix = np.fix(random_array) #Rounds toward zero, similar to np.trunc.
print("Integer part (fix):", integer_part_fix)

# Extract integer part using np.vectorize with int
integer_part_vectorize = np.vectorize(int)(random_array) #Applies to int function element-wise to the array.
print("Integer part (vectorize):", integer_part_vectorize)

Original array:  [3.79454448 6.98759577 1.14077769 5.08904016 7.41586072]
Integer part (floor): [3. 6. 1. 5. 7.]
Integer part (trunc): [3. 6. 1. 5. 7.]
Integer part (astype): [3 6 1 5 7]
Integer part (fix): [3. 6. 1. 5. 7.]
Integer part (vectorize): [3 6 1 5 7]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4


In [39]:
# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.zeros((5,5))
print(matrix)
# This generates an array with values [0, 1, 2, 3, 4]. Then, it adds the array [0, 1, 2, 3, 4] to each row of the matrix
matrix += np.arange(5)
print(" ")
print(matrix)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
 
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38. Consider a generator function that generates 10 integers and use it to build an array

In [40]:
def generate_integers():
    for i in range(10):
        # First Call: When the generator is first called, it starts executing the function until it hits the yield statement. 
        #     It returns the value of i and pauses.
        # Subsequent Calls: Each subsequent call to the generator resumes execution right after the yield statement, 
        #     continues until it hits the next yield, and pauses again.
        yield i
# Create the generator
generator = generate_integers()

# Build the Numpy array from the generator
# np.fromiter: This function constructs a 1-D array from an iterable (in this case, the generator).
# The dtype parameter specifies the desired data type of the array elements
array_from_generator = np.fromiter(generator, dtype=int) #
print(array_from_generator)

[0 1 2 3 4 5 6 7 8 9]


### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [41]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.linspace(0, 1, 12, endpoint= True)[1:-1]
# np.linspace(0, 1, 12, endpoint=True): This generates 12 evenly spaced values between 0 and 1, inclusive.
# [1:-1]: This slices the array to exclude the first and last elements, resulting in 10 values between 0 and 1.
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40. Create a random vector of size 10 and sort it

In [42]:
# Create a random vector of size 10
random_vector = np.random.random(10)
print("Original:", random_vector)
print(" ")
# Sort the array
random_vector.sort()
print("Sorted array:", random_vector)

Original: [0.85248578 0.14020916 0.59534432 0.63443343 0.7567617  0.23273052
 0.92438345 0.17214323 0.5319059  0.37440281]
 
Sorted array: [0.14020916 0.17214323 0.23273052 0.37440281 0.5319059  0.59534432
 0.63443343 0.7567617  0.85248578 0.92438345]


### 41. How to sum a small array faser than np.sum?

In [47]:
# Using Python's buil-in sum function
array = np.array([1, 2, 3, 4, 5])
result = sum(array)
print(result)

# Using np.eisum
# This function is highly optimized for various operations, including summation, and can be faster for certain array types
result = np.einsum('i->', array)
print(result)

# Using np.add.reduce
# This is another NumPy function that can be faster than np.sum for small arrays due to reduced overhead.
result = np.add.reduce(array)
print(result)

15
15
15


### 42. Consider two random array A and B, check if they are equal

In [48]:
# To check if two random arrays A and B are equal, you can use NumPy's array_equal function.
# The function compares two arrays element-wise and return True if they are exactly the same, and False otherwise.
A = np.random.rand(5) 
B = np.random.rand(5) 

# Check if they are equal
are_equal = np.array_equal(A, B)
print("Array A:", A)
print("Array B:", B)
print("Are the arrays equal?", are_equal)


Array A: [0.17694504 0.80465987 0.8061872  0.11818561 0.28852408]
Array B: [0.81166954 0.39284172 0.39616327 0.41017786 0.39820323]
Are the arrays equal? False


### 43. Make an array immutable (read-only)

In [50]:
# To make a Numpy array immutable (read-only), you can set it writable flag to False
# Create a sample array
array = np.array([1, 2, 3, 4, 5])
# Make the array imutable
array.flags.writeable = False 
# Trying to modify the array will now raise an error
try:
    array[0] = 10 
except ValueError as e:
    print("Error:", e)

Error: assignment destination is read-only


### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [57]:
# Generate a random 10x2 matrix representing Cartesian cooridates
cartesian_coords = np.random.rand(10,2) 
print(cartesian_coords)
# Separate the x and y coordinates 
X = cartesian_coords[:,0]
y = cartesian_coords[:,1]

# Convert to polar coordinates
r = np.sqrt(X**2 + y**2)
theta = np. arctan2(y,X)
print(" ")
print(r)
print(" ")
print(theta)

# Combine r and theta into a single array
polar_coords = np.column_stack((r, theta))
print(" ")
print("Cartesian coordinates:\n", cartesian_coords)
print(" ")
print("Polar coordinates:\n", polar_coords)

[[0.45158826 0.79040281]
 [0.93870959 0.95654868]
 [0.38536126 0.09566629]
 [0.1364778  0.1380374 ]
 [0.21174928 0.46129985]
 [0.10314732 0.45027763]
 [0.44733389 0.26194015]
 [0.76529385 0.51835114]
 [0.66253627 0.4953547 ]
 [0.87544034 0.66828051]]
 
[0.91031234 1.34020934 0.39705836 0.19411469 0.50757789 0.46194081
 0.51838234 0.92431736 0.82724276 1.10136036]
 
[1.05171744 0.79481037 0.24333181 0.79107937 1.1404606  1.34560669
 0.52973305 0.59534384 0.64200458 0.65199998]
 
Cartesian coordinates:
 [[0.45158826 0.79040281]
 [0.93870959 0.95654868]
 [0.38536126 0.09566629]
 [0.1364778  0.1380374 ]
 [0.21174928 0.46129985]
 [0.10314732 0.45027763]
 [0.44733389 0.26194015]
 [0.76529385 0.51835114]
 [0.66253627 0.4953547 ]
 [0.87544034 0.66828051]]
 
Polar coordinates:
 [[0.91031234 1.05171744]
 [1.34020934 0.79481037]
 [0.39705836 0.24333181]
 [0.19411469 0.79107937]
 [0.50757789 1.1404606 ]
 [0.46194081 1.34560669]
 [0.51838234 0.52973305]
 [0.92431736 0.59534384]
 [0.82724276 0.64200

### 45. Create a random vector of size 10 and replace the maximum value by 0

In [62]:
# Create a random vector of size 10
vector = np.random.rand(10)
print("vector:\n", vector)

# Find the index of the maximum value 
max_index = vector.argmax()
print(" ")
print("max_index:\n", max_index)

# Replace the maximum value with 0
vector[max_index] = 0 
print(" ")
print("Modified vector:\n", vector)

vector:
 [0.52525122 0.48721872 0.72050088 0.88924628 0.396901   0.24668292
 0.32690453 0.83090506 0.26444018 0.8406256 ]
 
max_index:
 3
 
Modified vector:
 [0.52525122 0.48721872 0.72050088 0.         0.396901   0.24668292
 0.32690453 0.83090506 0.26444018 0.8406256 ]


### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [70]:
# To create a structured array with (x) and (y) coordinates covering the ([0,1] x [0,1]) 
# area, we can use Numpy's meshgrid function along with a structured array
# Define the grid size
grid_size = 10 

# Create a structured array with 'x' and 'y'
structured_array = np.zeros((grid_size, grid_size), dtype=[('x', float), ('y', float) ])
print("structured_array:\n", structured_array)

# Generate the x and y coordinates
x,y = np.meshgrid(np.linspace(0,1, grid_size), np.linspace(0,1, grid_size))

# Assign the coordinates to the structured array
structured_array['x'], structured_array['y'] = x, y 
print(" ")
print("Structured array with x and y coordinates:\n ", structured_array)



structured_array:
 [[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]
 
Structured array with x and 