# 100 NumPy Exercises
Here is the reference to the original problem:https://github.com/maykulkarni/Machine-Learning-Notebooks/blob/master/00.%20NumPy%20Basics/100_Numpy_exercises_no_solution.ipynbs.

### 1. Import the numpy package under the name np

In [2]:
import numpy as np

### 2. Print the numpy version and the configuration

In [3]:
print("Numpy version: {}".format(np.__version__))
np.show_config()

Numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/men_l/anaconda3/Library/include
    lib directory: C:/Users/men_l/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: win

### 3. Create a null vector of size 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array

In [5]:
a = np.zeros(10)
print("Size of one element: {}".format(a.itemsize))
print("Size of the entire array: {}". format(a.nbytes))

Size of one element: 8
Size of the entire array: 80


### 5. How to get the documentation of the numpy add function from the command line?

In [6]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------

### 6. Create a null vector of size 10 but the fifth value which is 1

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last)

In [9]:
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

### 11. Create a 3x3 identity matrix

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values

In [13]:
np.random.randint(0,100,(3,3,3))

array([[[18,  1, 78],
        [44,  2, 47],
        [80, 28, 81]],

       [[92, 22, 40],
        [15, 75, 34],
        [69, 12, 15]],

       [[ 5, 90,  4],
        [97, 49, 41],
        [40, 72, 90]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values 


In [15]:
rand_array = np.random.randint(0,100,(10,10))
print("Arr: {}".format(rand_array))
print("Min: {}".format(np.min(rand_array)))
print("Max: {}".format(np.max(rand_array)))

Arr: [[20 50 86 76 39 31 30 65 40 27]
 [30 88 64 62  8 21 94 45 36 98]
 [61 91 45  5 30 57 26 10 96 25]
 [23 66 15 64 21 66 82 69 10 20]
 [34 99 96 85 88 30 50 55 89 73]
 [73 48 96 57 98 63 65 67 29 18]
 [78 79 80 10  4 15 90 69  5 35]
 [68 72 51 57 74 45 17 76  0 42]
 [ 1  1 90  1 42  3  9 44 83 71]
 [74  9 92 72  3 81 89 36 58 44]]
Min: 0
Max: 99


### 14. Create a random vector of size 30 and find the mean value

In [17]:
rand_array = np.random.randint(1,30, (30))
print("Arr: {}".format(rand_array))
print("Mean: {}".format(rand_array.mean()))

Arr: [14 25 27 26 10 28 28  8 26 29  4 18 12 27 21  6 18  8  6 14 14 16  5 14
 24 16  6 16  8 26]
Mean: 16.666666666666668


### 15. Create a 2d array with 1 on the border and 0 inside 

In [21]:
# creates a 10x10 NumPy array filled with ones
arr = np.ones((10,10))
print("Before: ")
print(arr)
# arr[1:-1]: This selects rows from the second row (index 1) up to but not including the last row (index -1).
# arr[1:-1, 1:-1]: This further selects columns from the second column (index 1) up to but not including the last column (index -1).
# = 0: This assigns the value 0 to all elements within the selected range, effectively setting the inner portion of the array to zero
arr[1:-1, 1:-1] = 0 
print("\nAfter: ")
print(arr)

Before: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

After: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16 How to add a border (filled with 0's) around an existing array?

In [23]:
array = np.ones((3,3))
bordered_array  = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Original array: ")
print(array)
print("\nArray with border: ")
print(bordered_array)

Original array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with border: 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? (★☆☆)
> 0 * np.nan

> np.nan == np.nan

> np.inf > np.nan

> np.nan - np.nan

> 0.3 == 3 * 0.1

In [27]:
print(0*np.nan)
print(" ")
print(np.nan==np.nan)
print(" ")
print(np.inf>np.nan)
print(" ")
print(np.nan - np.nan)
print)


nan
 
False
 
False
 
nan
