# 100 NumPy Exercises
Here is the reference to the original problem:https://github.com/maykulkarni/Machine-Learning-Notebooks/blob/master/00.%20NumPy%20Basics/100_Numpy_exercises_no_solution.ipynbs.

### 1. Import the numpy package under the name np

In [2]:
import numpy as np
from numpy.lib import stride_tricks

### 2. Print the numpy version and the configuration

In [3]:
print("Numpy version: {}".format(np.__version__))
np.show_config()

Numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/men_l/anaconda3/Library/include
    lib directory: C:/Users/men_l/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: win

### 3. Create a null vector of size 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array

In [5]:
a = np.zeros(10)
print("Size of one element: {}".format(a.itemsize))
print("Size of the entire array: {}". format(a.nbytes))

Size of one element: 8
Size of the entire array: 80


### 5. How to get the documentation of the numpy add function from the command line?

In [6]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------

### 6. Create a null vector of size 10 but the fifth value which is 1

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last)

In [9]:
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

### 11. Create a 3x3 identity matrix

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values

In [13]:
np.random.randint(0,100,(3,3,3))

array([[[ 6, 54, 95],
        [47, 88, 56],
        [42, 95, 79]],

       [[12, 37, 22],
        [75, 23, 42],
        [66, 32, 33]],

       [[20, 85, 31],
        [14, 88, 14],
        [ 9, 50,  9]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values 


In [14]:
rand_array = np.random.randint(0,100,(10,10))
print("Arr: {}".format(rand_array))
print("Min: {}".format(np.min(rand_array)))
print("Max: {}".format(np.max(rand_array)))

Arr: [[34 81 12 13 70 17 57 61 60 17]
 [82 62 54 37 40 27 97 14  0 99]
 [35 20 21 16 42 96 75 25 18 81]
 [42 31 59 83 50 42 44 93 84 12]
 [51 95 25 84 35 68  2  4 19 98]
 [88 52 50 77 69 56 67 72 23  4]
 [ 6 67  0  2 69 32 76 49 83  2]
 [ 9 81  5 61 94 13 71 17 96 82]
 [ 6 98 27 79 54 83 71 38 70 27]
 [75 37 30 31 41  5 35 67 27 44]]
Min: 0
Max: 99


### 14. Create a random vector of size 30 and find the mean value

In [15]:
rand_array = np.random.randint(1,30, (30))
print("Arr: {}".format(rand_array))
print("Mean: {}".format(rand_array.mean()))

Arr: [17 13 27 23 24  7 14 26 18  7 20  3 14 17  4 27 26  9 12 18 21 10  7  3
  3 29 26 27  4 29]
Mean: 16.166666666666668


### 15. Create a 2d array with 1 on the border and 0 inside 

In [16]:
# creates a 10x10 NumPy array filled with ones
arr = np.ones((10,10))
print("Before: ")
print(arr)
# arr[1:-1]: This selects rows from the second row (index 1) up to but not including the last row (index -1).
# arr[1:-1, 1:-1]: This further selects columns from the second column (index 1) up to but not including the last column (index -1).
# = 0: This assigns the value 0 to all elements within the selected range, effectively setting the inner portion of the array to zero
arr[1:-1, 1:-1] = 0 
print("\nAfter: ")
print(arr)

Before: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

After: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array?

In [17]:
array = np.ones((3,3))
bordered_array  = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Original array: ")
print(array)
print("\nArray with border: ")
print(bordered_array)

Original array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with border: 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? (★☆☆)
> 0 * np.nan

> np.nan == np.nan

> np.inf > np.nan

> np.nan - np.nan

> 0.3 == 3 * 0.1

In [18]:
print(0*np.nan)
print(" ")
print(np.nan==np.nan)
print(" ")
print(np.inf>np.nan)
print(" ")
print(np.nan - np.nan)
print(" ")
print(0.3 == 3*0.1)


nan
 
False
 
False
 
nan
 
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [19]:
# Create a 5x5 matrix of zeros
matrix = np.zeros((5,5), dtype=int)
print(matrix)
print(" ")

# Assign values 1,2,3,4 just below the diagonal
for i in range(1,5):
    # matrix[i, i-1]: This part accesses the element in the matrix at the row index i and column index i-1. 
    # In a 5x5 matrix, i ranges from 0 to 4. However, in the loop, i starts from 1 to 4, so i-1 ranges from 0 to 3.
    # = i: This assigns the value of i to the element at the specified position in the matrix.
    matrix[i , i-1] = i
print(matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix  and fill it with a checkboard pattern

In [20]:
# Create a 8x8 matrix of zero 
matrix = np.zeros((8,8), dtype = int)
print(matrix)
print(" ")
# Fill the matrix with a checkboard pattern
# This sets every other element in every other row, starting from the second row (index 1), to 1
matrix[1::2, ::2]= 1
print(matrix)
print(" ")

# This sets every other element in every other column, starting from the second column (index 1), to 1
matrix[::2, 1::2] = 1
print("This results in a checkerboard pattern where 1s and 0s alternate: ")
print(matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
 
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
 
This results in a checkerboard pattern where 1s and 0s alternate: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
# Define the shape of the array
shape = (6,7,8)
print(shape)
print(" ")

# Find the index of the 100th element (remember to subtract 1 because indexing starts at 0)
# This function takes the flat index (99, since indexing starts at 0) and the shape of the array, and returns the corresponding multi-dimensional index
index = np.unravel_index(99, shape)
print("So, the index ((x, y, z)) of the 100th element in a ((6, 7, 8)) shaped array is ((1, 5, 3))")
print(index)

(6, 7, 8)
 
So, the index ((x, y, z)) of the 100th element in a ((6, 7, 8)) shaped array is ((1, 5, 3))
(1, 5, 3)


### 21. Create a checkboard 8x8 matrix using the tile function

In [22]:
# This creates a 2x2 matrix with a checkerboard pattern
pattern = np.array([[0,1], [1,0]])
print(pattern)
print(" ")
# Tile the pattern to create an 8x8 matrix
checkerboard = np.tile(pattern, (4,4)) #This tiles the 2x2 pattern to create an 8x8 matrix by repeating the pattern 4 times along both dimensions
print(checkerboard)

[[0 1]
 [1 0]]
 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix 

In [23]:
# Create a 5x5 matrix with random values 
matrix = np.random.rand(5,5)
# Normalize the matrix
# Subtracting the minimum value from each element and then dividing by the range (max - min) normalizes the values
# This formula scales the values in the matrix to be between 0 and 1
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix)-np.min(matrix))
print("Original Matrix:\n ", matrix)
print(" ")
print("Normalized Matirx:\n ", normalized_matrix)

Original Matrix:
  [[0.29936152 0.31973947 0.46051782 0.20265355 0.04975888]
 [0.39556586 0.01182728 0.30261753 0.8325634  0.03797532]
 [0.55528656 0.51917132 0.21331996 0.76873722 0.15810813]
 [0.73714075 0.4834396  0.90163312 0.93056918 0.1698018 ]
 [0.44708139 0.65736671 0.03023096 0.77046835 0.69786902]]
 
Normalized Matirx:
  [[0.3129652  0.33514548 0.48837497 0.20770389 0.04128646]
 [0.41767833 0.         0.31650919 0.8933261  0.0284607 ]
 [0.59152552 0.55221607 0.2193137  0.82385481 0.15921866]
 [0.7894638  0.51332405 0.96850469 1.         0.17194658]
 [0.47375015 0.70263415 0.02003139 0.82573906 0.74671868]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [24]:
# Define the custom dtype
color_dtype = np.dtype([
    #This defines a custom data type with four fields: ‘r’, ‘g’, ‘b’, and ‘a’, each of which is an unsigned byte (np.ubyte)
    ('r', np.ubyte), # Red channel 
    ('g', np.ubyte), # Green channel
    ('b', np.ubyte), # Blue channel
    ('a', np.ubyte)  # alpha channel
    
])
# Example of creating an array with this dtype
# This creates an array of colors using the custom dtype. Each color is represented as a tuple of four unsigned bytes
colors = np.array([(255,0,0,255), (0,255,0,255), (0,0,255,255)], dtype=color_dtype)
print(" This code output an array of colors with the specified RGBA: \n", colors)

 This code output an array of colors with the specified RGBA: 
 [(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [25]:
# Generates a 5x3 matrix with random values between 0 and 1
matrix1 = np.random.rand(5,3)
# Generates a 3x2 matrix with random values between 0 and 1
matrix2 = np.random.rand(3,2)
# Computes the dot product of the two matrices, resulting in a 5x2 matrix
result = np.dot(matrix1, matrix2)
print("First Matrix (5x3):\n", matrix1)
print(" ")
print("Second Matrix (3x2):\n", matrix2)
print(" ")
print("It will output the original matrices and their product. The resulting matrix will have the shape (5, 2):\n", result)

First Matrix (5x3):
 [[0.28334504 0.25176112 0.28885411]
 [0.84311384 0.357382   0.15052415]
 [0.67360531 0.18404592 0.67643737]
 [0.48198194 0.78821958 0.6641461 ]
 [0.50634506 0.24454144 0.9681155 ]]
 
Second Matrix (3x2):
 [[0.76334648 0.8437873 ]
 [0.2159187  0.68189234]
 [0.0536245  0.57765236]]
 
It will output the original matrices and their product. The resulting matrix will have the shape (5, 2):
 [[0.28614003 0.57761418]
 [0.72882522 1.04205543]
 [0.59020681 1.08462475]
 [0.57372506 1.3278167 ]
 [0.4912325  1.15323267]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [26]:
def negate_elements_in_range(arr):
    # Converts the input list arr into a NumPy array. NumPy arrays are more efficient for numerical operations compared to Python lists
    arr = np.array(arr)
    
    # Create a boolean mask. 
    # The expression (arr >= 3) creates a boolean array where elements are True if they are greater than or equal to 3
    # (arr <= 8) creates a boolean array where elements are True if they are less than or equal to 8
    # The & operator performs an element-wise logical AND operation, combining these two conditions
    mask = (arr>=3) & (arr<= 8)
   
    # This line uses the boolean mask to select elements of arr that meet the condition (i.e., elements between 3 and 8)
    # It then negates these selected elements in place. The -arr[mask] part negates the values, 
    # and arr[mask] = ... assigns the negated values back to their original positions in the array
    arr[mask] = -arr[mask]
    return arr 
# Example Usage
arr = [1, 4, 6, 9, 3, 8, 2]
negated_arr = negate_elements_in_range(arr)
print(negated_arr)

[ 1 -4 -6  9 -3 -8  2]


### 26. What is the output of the following script? 
> print(sum(range(5),-1))

> from numpy import *

> print(sum(range(5),-1))

In [27]:
# range(5): This generates a sequence of numbers from 0 to 4 (inclusive). So, range(5) produces [0, 1, 2, 3, 4]
# The sum function calculates the sum of the elements in the sequence generated by range(5), 
# but it also takes an optional second argument, which is the starting value for the sum. In this case, the starting value is -1
# So, the calculation proceeds as follows:
# Start with -1.
# Add the elements of the sequence [0, 1, 2, 3, 4] to -1
print(sum(range(5), -1))

from numpy import * #imports all functions and classes from the NumPy library into the current namespace
# Because of the from numpy import * statement, the sum function from NumPy is used instead of the built-in Python sum function
# range(5): This generates a sequence of numbers from 0 to 4 (inclusive). So, range(5) produces [0, 1, 2, 3, 4]
# The NumPy sum function does not use the second argument as a starting value for the sum. 
# Instead, it interprets the second argument as the axis parameter, which specifies the axis along which to sum the elements
# Since -1 is not a valid axis for a 1D array, NumPy ignores it and simply sums the elements of the array [0, 1, 2, 3, 4]
# Therefore, print(sum(range(5), -1)) outputs 10 because the second argument is ignored by NumPy’s sum function in this context
print(sum(range(5),-1))

9
10


### 27. Consider an integer vector Z, which of these expressions are legal?
> Z**Z

> 2 << Z >> 2

> Z <- Z

>1 j * Z

>Z/1/1

> Z < Z > Z  

1. `Z**Z`:
   
   &bull; This expression attempts to raise each element of `Z` to the power of the corresponding element in `Z`. This is legal in Numpy.

   &bull; `Legal` 
2. `2 << Z >> 2`:

    &bull; This expression involves bitwise left and right shifts. `2 << Z` shifts the number 2 to the left by each element in `Z`, and then `>> 2` shifts the result to the right by 2. This is legal in Numpy.

   &bull; `Legal`

3. `Z <- Z`:

   &bull; This expression is not valid in Python. The `<-` operator is not defined in Python.

   &bull; `Illegal`

4. `1j*Z`:

   &bull; This expression multiplies each element of `Z` by the imaginary until `1j`. This is legal in Numpy and results in a complex array.

   &bull; `Legal`

5. `Z/1/1`:

   &bull; This expression divides each element of `Z` by 1 twice. This is legal in Numpy.

   &bull; `Legal`

6. `Z<Z>Z`:

   &bull; This expression is not valid in Python. Chained comparisons like this are not supported.

   &bull; `Illegal`.
   
   
   


### 28. What are the result of the following expressions?
> np.array(0) / np.array(0)

> np.array(0) // np.array(0)

> np.array([np.nan]).astype(int).astype(float) 

In [28]:
# This expression attempts to divide zero by zero.
# In NumPy, this results in a division by zero, which produces a NaN (Not a Number) and raises a runtime warning
np.array(0) / np.array(0)



C:\Users\men_l\AppData\Local\Temp\ipykernel_26996\164202812.py:3: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [29]:
# This expression attempts to perform integer division of zero by zero. 
# In NumPy, this also results in a division by zero, which produces 0 and raises a runtime warning
np.array(0) // np.array(0)



C:\Users\men_l\AppData\Local\Temp\ipykernel_26996\1784414740.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [30]:
# This expression first creates a NumPy array containing NaN.
# It then attempts to cast this array to an integer type. Converting NaN to an integer is not well-defined and typically results in an undefined value,
# often -9223372036854775808 (the minimum value for a 64-bit integer).
# Finally, it casts the integer array back to a float
np.array([np.nan]).astype(int).astype(float)

C:\Users\men_l\AppData\Local\Temp\ipykernel_26996\3233124507.py:5: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

### 29. How to round away from zero a float array?

In [31]:
def round_away_from_zero(arr):
    # np.abs(arr): Takes the absolute value of each element in the array
    # np.ceil(np.abs(arr)): Rounds each element up to the nearest integer
    # np.copysign(np.ceil(np.abs(arr)), arr): Applies the sign of the original elements to the rounded values, effectively rounding away from zero
    return np.copysign(np.ceil(np.abs(arr)),arr)

# Expmaple usage:
arr = np.array([-1.5, -0.2, 0.2, 1.5, 2.3, -2.3])
rounded_arr = round_away_from_zero(arr)
print(rounded_arr)

[-2. -1.  1.  2.  3. -3.]


### 30. How to find common values between two arrays?

In [32]:
array1  = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)
print(common_values)

[3 4 5]


### 31. How to ignore all numpy warnings(not recommended)?

In [33]:
# Ignore all warnings
np.seterr(all='ignore')

# Example usage
arr = np.array([1,2,3])
print(arr/0) # This will not raise a warning

[inf inf inf]


### 32. Is the following expressions true?
np.sqrt(-1) = np.emath.sqrt(-1)

In [34]:
np.sqrt(-1) == np.emath.sqrt(-1)


False

### 33. How to get the dates of yesterday, today and tomorrow?

In [35]:
# Today's date
today= np.datetime64('today', 'D')
print("Today:", today)
# Yesterday's date
yesterday = today - np.timedelta64(1, 'D')
print("Yesterday: ", yesterday)
# Tomorrow's date
tomorrow = today + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Today: 2024-10-09
Yesterday:  2024-10-08
Tomorrow:  2024-10-10


### 34. How to get all the dates corresponding to the month of July 2016?

In [36]:
# Define the state and end dates for July 2016
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

# Generate an array of all dates in July 2016
july_dates = np.arange(start_date, end_date, dtype='datetime64[D]')
print(july_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [37]:
# Example arrays
A = np.array([1,2,3,4], dtype = float)
B = np.array([5,6,7,8], dtype = float)

# Step 1: Add A and B, store the result A (in-place)
A += B
# step 2: Multiply A by -0.5 (equivalent to -A/2), store the result in A (in-place)
A *= -0.5
print(A)

[-3. -4. -5. -6.]


### 36. Extract the integer part of a random array using 5 different methods

In [38]:
# Generate a random array
random_array = np.random.random(5) * 10
print("Original array: ", random_array)

# Extract integer part using np.floor
integer_part_floor = np.floor(random_array) # Rounds down to the nearest integer
print("Integer part (floor):", integer_part_floor)

# Extract integer part using np.trunc
integer_part_trunc = np.trunc(random_array) #Truncates the decimal part, effectively rounding towards zero
print("Integer part (trunc):", integer_part_trunc)

# Extract integer part by converting to int
integer_part_int = random_array.astype(int) #Converts the array elements to integers, truncating the decimal part.
print("Integer part (astype):", integer_part_int)

# Extract integer part using np.fix
integer_part_fix = np.fix(random_array) #Rounds toward zero, similar to np.trunc.
print("Integer part (fix):", integer_part_fix)

# Extract integer part using np.vectorize with int
integer_part_vectorize = np.vectorize(int)(random_array) #Applies to int function element-wise to the array.
print("Integer part (vectorize):", integer_part_vectorize)

Original array:  [7.63379146 2.03114469 0.89673307 0.57844005 8.79338363]
Integer part (floor): [7. 2. 0. 0. 8.]
Integer part (trunc): [7. 2. 0. 0. 8.]
Integer part (astype): [7 2 0 0 8]
Integer part (fix): [7. 2. 0. 0. 8.]
Integer part (vectorize): [7 2 0 0 8]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4


In [39]:
# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.zeros((5,5))
print(matrix)
# This generates an array with values [0, 1, 2, 3, 4]. Then, it adds the array [0, 1, 2, 3, 4] to each row of the matrix
matrix += np.arange(5)
print(" ")
print(matrix)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
 
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38. Consider a generator function that generates 10 integers and use it to build an array

In [40]:
def generate_integers():
    for i in range(10):
        # First Call: When the generator is first called, it starts executing the function until it hits the yield statement. 
        #     It returns the value of i and pauses.
        # Subsequent Calls: Each subsequent call to the generator resumes execution right after the yield statement, 
        #     continues until it hits the next yield, and pauses again.
        yield i
# Create the generator
generator = generate_integers()

# Build the Numpy array from the generator
# np.fromiter: This function constructs a 1-D array from an iterable (in this case, the generator).
# The dtype parameter specifies the desired data type of the array elements
array_from_generator = np.fromiter(generator, dtype=int) #
print(array_from_generator)

[0 1 2 3 4 5 6 7 8 9]


### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [41]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.linspace(0, 1, 12, endpoint= True)[1:-1]
# np.linspace(0, 1, 12, endpoint=True): This generates 12 evenly spaced values between 0 and 1, inclusive.
# [1:-1]: This slices the array to exclude the first and last elements, resulting in 10 values between 0 and 1.
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40. Create a random vector of size 10 and sort it

In [42]:
# Create a random vector of size 10
random_vector = np.random.random(10)
print("Original:", random_vector)
print(" ")
# Sort the array
random_vector.sort()
print("Sorted array:", random_vector)

Original: [0.3197995  0.72425204 0.02702153 0.67214097 0.67155838 0.72354862
 0.7604888  0.01255445 0.40441954 0.47362854]
 
Sorted array: [0.01255445 0.02702153 0.3197995  0.40441954 0.47362854 0.67155838
 0.67214097 0.72354862 0.72425204 0.7604888 ]


### 41. How to sum a small array faser than np.sum?

In [43]:
# Using Python's buil-in sum function
array = np.array([1, 2, 3, 4, 5])
result = sum(array)
print(result)

# Using np.eisum
# This function is highly optimized for various operations, including summation, and can be faster for certain array types
result = np.einsum('i->', array)
print(result)

# Using np.add.reduce
# This is another NumPy function that can be faster than np.sum for small arrays due to reduced overhead.
result = np.add.reduce(array)
print(result)

15
15
15


### 42. Consider two random array A and B, check if they are equal

In [44]:
# To check if two random arrays A and B are equal, you can use NumPy's array_equal function.
# The function compares two arrays element-wise and return True if they are exactly the same, and False otherwise.
A = np.random.rand(5) 
B = np.random.rand(5) 

# Check if they are equal
are_equal = np.array_equal(A, B)
print("Array A:", A)
print("Array B:", B)
print("Are the arrays equal?", are_equal)


Array A: [0.61576091 0.59125657 0.98537219 0.20001445 0.72978409]
Array B: [0.42273673 0.50757678 0.32803427 0.08530388 0.01145546]
Are the arrays equal? False


### 43. Make an array immutable (read-only)

In [45]:
# To make a Numpy array immutable (read-only), you can set it writable flag to False
# Create a sample array
array = np.array([1, 2, 3, 4, 5])
# Make the array imutable
array.flags.writeable = False 
# Trying to modify the array will now raise an error
try:
    array[0] = 10 
except ValueError as e:
    print("Error:", e)

Error: assignment destination is read-only


### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [46]:
# Generate a random 10x2 matrix representing Cartesian cooridates
cartesian_coords = np.random.rand(10,2) 
print(cartesian_coords)
# Separate the x and y coordinates 
X = cartesian_coords[:,0]
y = cartesian_coords[:,1]

# Convert to polar coordinates
r = np.sqrt(X**2 + y**2)
theta = np. arctan2(y,X)
print(" ")
print(r)
print(" ")
print(theta)

# Combine r and theta into a single array
polar_coords = np.column_stack((r, theta))
print(" ")
print("Cartesian coordinates:\n", cartesian_coords)
print(" ")
print("Polar coordinates:\n", polar_coords)

[[0.77638344 0.77171676]
 [0.51576521 0.11940991]
 [0.35618436 0.00778561]
 [0.37877202 0.58619681]
 [0.96178454 0.49026816]
 [0.23118116 0.07092837]
 [0.04324425 0.3509197 ]
 [0.65490932 0.94616501]
 [0.76920189 0.59944284]
 [0.82606614 0.50016178]]
 
[1.09467712 0.52940766 0.35626944 0.69792188 1.0795334  0.24181721
 0.35357418 1.15071041 0.97519396 0.96568477]
 
[0.78238371 0.22751144 0.02185489 0.99713123 0.4714159  0.29769147
 1.4481833  0.96534312 0.66199401 0.54443497]
 
Cartesian coordinates:
 [[0.77638344 0.77171676]
 [0.51576521 0.11940991]
 [0.35618436 0.00778561]
 [0.37877202 0.58619681]
 [0.96178454 0.49026816]
 [0.23118116 0.07092837]
 [0.04324425 0.3509197 ]
 [0.65490932 0.94616501]
 [0.76920189 0.59944284]
 [0.82606614 0.50016178]]
 
Polar coordinates:
 [[1.09467712 0.78238371]
 [0.52940766 0.22751144]
 [0.35626944 0.02185489]
 [0.69792188 0.99713123]
 [1.0795334  0.4714159 ]
 [0.24181721 0.29769147]
 [0.35357418 1.4481833 ]
 [1.15071041 0.96534312]
 [0.97519396 0.66199

### 45. Create a random vector of size 10 and replace the maximum value by 0

In [47]:
# Create a random vector of size 10
vector = np.random.rand(10)
print("vector:\n", vector)

# Find the index of the maximum value 
max_index = vector.argmax()
print(" ")
print("max_index:\n", max_index)

# Replace the maximum value with 0
vector[max_index] = 0 
print(" ")
print("Modified vector:\n", vector)

vector:
 [0.85888027 0.61235637 0.93270001 0.04346409 0.98309699 0.64149261
 0.79346779 0.60807556 0.21880934 0.66288841]
 
max_index:
 4
 
Modified vector:
 [0.85888027 0.61235637 0.93270001 0.04346409 0.         0.64149261
 0.79346779 0.60807556 0.21880934 0.66288841]


### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [48]:
# To create a structured array with (x) and (y) coordinates covering the ([0,1] x [0,1]) 
# area, we can use Numpy's meshgrid function along with a structured array
# Define the grid size
grid_size = 10 

# Create a structured array with 'x' and 'y'
structured_array = np.zeros((grid_size, grid_size), dtype=[('x', float), ('y', float) ])
print("structured_array:\n", structured_array)

# Generate the x and y coordinates
x,y = np.meshgrid(np.linspace(0,1, grid_size), np.linspace(0,1, grid_size))

# Assign the coordinates to the structured array
structured_array['x'], structured_array['y'] = x, y 
print(" ")
print("Structured array with x and y coordinates:\n ", structured_array)



structured_array:
 [[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]
 
Structured array with x and 

### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1(/Xi-Yj))

In [49]:
# Example arrays
x = np.array([1,2,3])
y = np.array([4,5,6])

# Constructing the Cauchy matrix
C = 1.0/(x[:, np.newaxis]- y)
# X[:, np.newaxis] reshapes X to a column vector
# The subtraction X[:, np.newaxis] - Y creates a matrix where each element is the difference between elements of X and Y
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


### 48. Print the minimum and maximum representable value for each numpy scalar type

In [50]:
import numpy as np

# np.sctypes: This attribute of the NumPy module returns a sequence containing all scalar data types supported by NumPy. 
# These data types include integers, floating-point numbers, complex numbers, booleans, and more.
for dtype in np.sctypes:

    #  Directly check if the dtype name starts with characters representing integer types. 
    # This works because standard integer type names in NumPy usually begin with 'i', 'u', or 'b' (signed integer, unsigned integer, and boolean)
  if str(dtype)[0] in ('i', 'u', 'b'):  
    print(f"dtype: {dtype}")
    print(f"Minimum value: {np.iinfo(dtype).min}")
    print(f"Maximum value: {np.iinfo(dtype).max}")
    print()

dtype: int
Minimum value: -2147483648
Maximum value: 2147483647

dtype: uint
Minimum value: 0
Maximum value: 4294967295



### 49. How to print all the values of an array

In [51]:
arr = np.array([1,2,3,4,5])
# 1. Using print() directly
print(arr)
print()
# 2. Using np.array2string()
print(np.array2string(arr))
print()
# 3. Using a loop
for value in arr:
    print(value)

[1 2 3 4 5]

[1 2 3 4 5]

1
2
3
4
5


### 50. How to find the closest value (to a given scalar) in a vector

In [52]:
# Example array and scalar
arr = np.array([1,3,8,10,15])
scalar = 9 

# Calculate the absolute differences
differences = np.abs(arr - scalar)
print("differences:\n", differences)

# Find the index of the minimum difference
index_of_min = np.argmin(differences)
print()
print("index_of_min:\n", index_of_min)

# Get the closest value
closest_value = arr[index_of_min]
print()
print(f"The closet value to {scalar} is {closest_value}")

differences:
 [8 6 1 1 6]

index_of_min:
 2

The closet value to 9 is 8


### 51. Create a structured array representing a position (x,y) and a color (r,g,b) 

In [53]:
"""To create a structured array in Numpy that represents a position (x,y) and a color (r,g,b), 
we can define a custom data type and then create the array using  that data type."""
# Define the data type with fields for position and color
# Define a structured data type with two fields: position (containing x and y coordinates) and color (containing r, g, and b values)
dtype = np.dtype([
    ('position', [('x', np.float32), ('y', np.float32)]),
    ('color', [('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])
])
# Create a structured array with the defined data type
data = np.array([
    ((1.0,2.0), (255,0,0)),
    ((3.0,4.0), (0,255,0)),
    ((5.0, 6.0), (0,0,255))
], dtype=dtype)

# Accessing the data
print(data)
print("First position:", data['position'][0])
print("First color:", data['color'][0])

[((1., 2.), (255,   0,   0)) ((3., 4.), (  0, 255,   0))
 ((5., 6.), (  0,   0, 255))]
First position: (1., 2.)
First color: (255, 0, 0)


### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [54]:
# Generate a random vector with shape (100,2)
coordinates = np.random.rand(100,2)

# Calculate the pairwise distances
    # coordinates[:, np.newaxis] adds a new axis to coordinates, changing its shape from (100, 2) to (100, 1, 2). 
        # This effectively turns each 2D coordinate into a 1x2 array, allowing for broadcasting in the next step
    # coordinates[:, np.newaxis] - coordinates:
        # Here, we subtract the original coordinates array (shape (100, 2)) from the expanded coordinates array (shape (100, 1, 2)).
        # Due to broadcasting, this operation results in an array of shape (100, 100, 2), 
        # where each element (i, j) is the difference between the i-th and j-th coordinates
    # np.linalg.norm(..., axis=2):
        # np.linalg.norm computes the Euclidean norm (or distance) along the specified axis.
        # By setting axis=2, we calculate the norm along the last axis of the (100, 100, 2) array, which corresponds to the 2D differences between points.
        # This results in a (100, 100) array where each element (i, j) represents the Euclidean distance between the i-th and j-th points
distances = np.linalg.norm(coordinates[:, np.newaxis] - coordinates, axis=2)

print(distances)

[[0.         0.39664446 1.06304452 ... 0.61088882 0.49944029 0.71150537]
 [0.39664446 0.         0.82845775 ... 0.52729352 0.58184722 0.31538146]
 [1.06304452 0.82845775 0.         ... 0.49330729 0.71797656 0.72290407]
 ...
 [0.61088882 0.52729352 0.49330729 ... 0.         0.23412396 0.63364261]
 [0.49944029 0.58184722 0.71797656 ... 0.23412396 0.         0.78071059]
 [0.71150537 0.31538146 0.72290407 ... 0.63364261 0.78071059 0.        ]]


### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

To convert a float (32) array into an array (32 bits) array in place using Numpy, we can use the `astype` method. However, 
note that `astype` does not modify the array in place; it creates a new array. To achieve an in-place conversion, we can use the `view`
method to reinterpret the data type and then assign the values back.

In [55]:
# Create a float32 array
float_array = np.random.rand(10).astype(np.float32)
# Convert the float array to int32 in place
float_array[:] = float_array.view(np.int32)
print(float_array)

[1.04044435e+09 1.04627430e+09 1.06312102e+09 1.05202880e+09
 1.05834778e+09 1.06327674e+09 1.06478515e+09 1.06128992e+09
 1.04328890e+09 1.03918458e+09]


### 54. How to read the following file? 
>1, 2, 3, 4, 5

>6,  ,  , 7, 8

>,  , 9,10,11 

To read a file with missing values, we can use the pandas.read_csv function, which handles missing values gracefully. 

In [56]:
# Create a sample file with the given data 
with open('sample.csv', 'w') as file:
        file.write("1, 2, 3, 4, 5\n")
        file.write("6,  ,  , 7, 8\n")
        file.write(" ,  , 9,10,11\n")
# Read the the file into a DataFrame
df = pd.read_csv('sample.csv', header= None, skipinitialspace= True)
# header=None indicates that the file does not have a header row
# skipinitialspace=True ensures that any spaces after the commas are ignored 

print(df)

NameError: name 'pd' is not defined

### 55. What is the equivalent of enumerate for numpy arrays?

The equivalent of `enumerate` for Numpy arrays is `np.ndenumerate`. This
function allows you to iterate over a Numpy array while getting both the index and the value of each element.

In [ ]:
# Example with a 1D array
arr = np.array([10,20,30,40])
for index, value in np.ndenumerate(arr):
    print(index, value)
print()
# Example with a 2D array
arr = np.array([[1,2], [3,4]])
for index, value in np.ndenumerate(arr):
    print(index, value)
    

### 56. Generate a generic 2D Gaussian-like array

In [ ]:
def generate_2d_gaussian(kernel_size, sigma=1.0):
    # Create a grid of (x, y) coordinate
    # np.linspace(-1, 1, kernel_size):
        # This function generates kernel_size evenly spaced values between -1 and 1.
        # For example, if kernel_size is 5, np.linspace(-1, 1, 5) would produce the array [-1, -0.5, 0, 0.5, 1].
    # np.meshgrid:
        #This function takes two 1D arrays and produces two 2D matrices (grids) from them.
        #The first array represents the x-coordinates and the second array represents the y-coordinates.
    x, y = np.meshgrid(np.linspace(-1,1, kernel_size), np.linspace(-1,1,kernel_size))
    
    # Calculate the distance from center
    d = np.sqrt(x**2 + y**2)

    # Calculate the Gaussian function
    g = np.exp(-((d**2)/ (2.0 * sigma**2)))

    # Normalize the Gaussian function
    g /= g.sum()

    return g
# Example usage
kernel_size = 5 
sigma = 1.0
gaussian_array = generate_2d_gaussian(kernel_size, sigma)
print(gaussian_array)

### 57. How to randomly place p elements in a 2D array?

In [ ]:
# Define the dimensions of the 2D array
row, cols = 5,5 

# Create an empty 2D array
array = np.zeros((row, cols))

# Define the number of elements to place
p = 10 

# Define the elements to place (can be any values you want)
elements = np.arange(1, p+1)

# Randomly choose positions in the array
positions = np.random.choice(row*cols, p, replace = False)

# Place the elements in the chosen positions
# zip(positions, elements):
# This function pairs each element in positions with the corresponding element in elements. 
    # For example, if positions = [3, 7, 12] and elements = [1, 2, 3], zip(positions, elements) will produce pairs like (3, 1), (7, 2), and (12, 3)
for pos, element in zip(positions, elements):
    array[pos// cols, pos % cols] = element 
print(array)


### 58. Subtract the mean of each row of a matrix

In [ ]:
# Create a sample 2D array (matrix)
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
# Calculate the mean of each row
    # This calculates the mean of each row. The axis=1 parameter specifies that the mean should be computed along the rows. 
    # The keepdims=True parameter ensures that the result has the same number of dimensions as the original matrix, which is necessary for broadcasting.
row_means = matrix.mean(axis=1, keepdims = True)

# Subtract the mean of each row from the corresponding row elements
result = matrix - row_means

print("Original matrix:\n", matrix)
print("Row means:\n", row_means)
print("Matrix after subtracting row means: \n", result)

### 59. How to sort an array by the nth column

In [ ]:
# Create a sample 2D array (matrix)
matrix = np.array([[9, 2, 3], 
                   [4, 5, 6], 
                   [7, 0, 5]])

# Define the column index to sort by (e.g., 1 for the second column)
n = 1 

# Get the indices that would sort the nth column
    # matrix[:, n]:
        #This extracts the ( n )-th column from the 2D array matrix. The colon (:) indicates that we want all rows, and n specifies the column index.
    # .argsort():
        # This function returns the indices that would sort the array. 
sorted_indices = matrix[:, n].argsort()
print("Sorted_indices: \n", sorted_indices)

# Use the sorted indices to reorder the rows of the matrix
sorted_matrix = matrix[sorted_indices]

print("Original matrix:\n", matrix)
print("Sorted matrix by column", n, ":\n", sorted_matrix)

### 60. How to tell if a given 2D array has null columns?

In [ ]:
# Example 2D array
array = np.array([[1, 0, 3],
    [4, 0, 6],
    [7, 0, 9]])

# Check for null columns
# array.any(axis=0) returns a boolean array where each element is True if the corresponding column has any non-zero elements, and False otherwise
# ~array.any(axis=0) inverts the boolean array, so True indicates a column with all zeros
null_columns = (~array.any(axis=0)).any()
print("Does the array have columns?", null_columns)

### 61. Find the nearest value from a given value in an array

In [ ]:
# Example array
array = np.array([10, 22, 14, 7, 33, 5, 18])

# Target value
target_value = 15

# Find the index of the nearest value
# .argmin() finds the index of the smallest difference.
index = np.abs(array - target_value).argmin()
print("index:\n",index)

# Get the nearest value
# array[index] retrieves the element at that index, which is the nearest value to the target
nearest_value = array[index]

print("The nearest value to", target_value, "is", nearest_value)

### 62. Considering two arrays with shape(1,3) and (3,1), how to compute their sum using an iterator?

To compute the sum of two arrays with shape (1,3) and (3,1) using an iterator, we can use the nditer function. This function allows us to iterate over arrays in a flexible way.

In [ ]:
# Create the arrays
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Allocates space for the result array
result = np.empty((3,3))
# Initialize an iterator with broadcasting enabled
# np.nditer is initialized with the two input arrays and the allocated result array
it = np.nditer([array1, array2, result], flags=['external_loop'], op_flags=[['readonly'], ['readonly'], ['writeonly']], op_axes=[None, None, [0, 1]])

# Compute the sum using the iterator
# The loop iterates over the elements of the arrays, computes their sum, and stores it in the result array
for x, y, z in it:
    z[...] = x + y

# Get the result array
result = it.operands[2]

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Sum:\n", result)


### 63. Create an array class that has a name attribute

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=""):
        
        """__new__ Method: This method is responsible for creating and returning a new instance of the class. 
        It uses np.asarray to convert the input array to an ndarray and then views it as an instance of NamedArray.
        The name attribute is added to the instance"""
        
        obj = np.asarray(input_array).view(cls)
        obj.name = name 
        return obj 

    def __array_finalize__(self,obj):

        """
        __array_finalize__ Method: This method ensures that the name attribute is preserved 
        when the array is sliced or viewed in different ways.
        """
        
        if obj is None:
            return 
        self.name = getattr(obj, 'name', "")

# Example usage
array = NamedArray([[1, 2, 3], [4, 5, 6]], name = "MyArray")
print("Array:\n", array)
print("Name:\n", array.name)

### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [ ]:
# Example vector
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Index vector (with repeated indices)
indices = np.array([1, 3, 3, 5, 7, 7, 7])

# Use np.add.at to add 1 to each element indexed by the indices
np.add.at(vector, indices, 1)

print("Updated vector:", vector)

### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

To accumulate elements of a vector (X) into an array (F) based on an index list (I), we can use the `np.add.at` function. This function allows us to perform unbuffered in-place operations on the array, which is useful for handling repeated indices correctly.

In [ ]:
# Example vector X
X =  np.array([1, 2, 3, 4, 5])

# Index list I
I = np.array([0, 1, 2, 1, 0])

# Array F initialized to zeros with the appropriate shape
F = np.zeros(3)

# Accumulate elements of X into F based on indices in I
np.add.at(F, I, X)

print("Vector X:", X)
print("Index list I:", I)
print("Accumulated array F:", F)


###  66. Considering a (w,h,3)  image of (dtype=ubyte), compute the number of unique colors


In [ ]:
# Assuming 'image' is your (w,h,3) image array of dtype 'ubyte'
image = np.random.randint(0, 256, (100, 100, 3), dtype=np.ubyte)

# Reshape the image to a 2D array where each row is a pixel and columns are RGB values
reshaped_image = image.reshape(-1,3)

# Find unique rows(unique colors)
unique_colors = np.unique(reshaped_image, axis=0)

# Count the number of unique colors
num_unique_colors = unique_colors.shape[0]

print(f"Number of unique colors: , {num_unique_colors}")



### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

To computer the sum over the last two axes of a four-dimensional array using Numpy, you can use the `numpy.sum` functino and specify the axes you want to sum over.

In [ ]:
# Example 4D array
array_4d = np.random.rand(2,3,4,5)

# Sum over the last two axes (axis 2 and axis 3)
sum_over_last_two_axes = np.sum(array_4d, axis=(-2,-1))

print("Sum over the last two axes:\n",sum_over_last_two_axes )


### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

To compute the means of subsets of a one-dimensional vector (D) using a vector (S) of the same size that describes subset indices, we can use a `biscount` and `unique` functions.

In [ ]:
# Example vectors 
D = np.array([10, 20, 30, 40, 50, 60])
S = np.array([1, 1, 2, 2, 1, 2])

# Find unique subset indices
unique_indices = np.unique(S)
print(f"unique_indices:\n {unique_indices}")

# Compute the sum and count for each subset
    # computes the sum of elements in D for each subset index in S
sum_per_subset = np.bincount(S, weights=D)
print(f"sum_per_subset:\n {sum_per_subset}")
    # computes the count of elements for each subset index in S
count_per_subset = np.bincount(S)
print(f"sum_per_subset\n {sum_per_subset}")

# Compute the mean for each subset
mean_per_subset = sum_per_subset / count_per_subset
print(f"mean_per_subset:\n {mean_per_subset }")

# Create a dictionary to map subset indices to their means
subset_means =dict(zip(unique_indices, mean_per_subset[unique_indices]))

print(f"Mean of subsets:\n {subset_means}")

### 69. How to get the diagonal of a dot product

To get the diagonal of a dot product of two matrices using Numpy, you can use the `np.dot` function to compute the dot product and then the `np.diag` function to extract the diagonal elements

In [ ]:
# Example matrices
a = np.random.rand(4,4)
b = np.random.rand(4,4)

# Compute the dot product
dot_product = np.dot(a,b)

# Extract the diagonal elements
diagonal_elements = np.diag(dot_product)

print(f"Dot product of matrices a and b: \n{dot_product}")
print(f"diagonal elements of the dot product: \n {diagonal_elements}")

### 70. Consider the vector [1,2,3,4,5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [ ]:
# Original vector
original_vector = np.array([1, 2, 3, 4, 5])
# Number of zeros to interleave
num_zeros = 3 
# Create a new array of the required size filled with zeros
new_vector = np.zeros(len(original_vector) + (len(original_vector)-1) * num_zeros, dtype=original_vector.dtype)
# Assign the values from the original vector to the correct positions in the new vector
new_vector[::num_zeros +1] = original_vector 

print(f"Original vector: \n {original_vector}")
print(f"New vector with interleaved zeros: \n {new_vector}")

### 71. Consider an array of dimension (5,5,3) how to multiply it by an array with dimensions(5,5)?


In [ ]:
# Create the arrays
array1 = np.random.rand(5,5,3)
array2 = np.random.rand(5,5)

# Multiply the arrays using broadcasting
# array2[:, :, np.newaxis] reshapes array2 from (5, 5) to (5, 5, 1), allowing it to broadcast across the third dimension of array1.
result = array1 * array2[:, :, np.newaxis]

print(result)

### 72. How to swap two rows of an array?

We can use advanced indexing to swap rows. For example, to swap the first and second rows:

In [ ]:
# Create an example array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Swap the first and second rows
array[[0,1]] = array[[1,0]]
print(array)

### 73. Consider a set of 10 triplets describing 10 triangles (with shared verticles), find the set of unique line segments composing all the triangles

In [ ]:
# Example array of 10 triplets (each triplet represents a triangle)
triangles = np.array([[0, 1, 2],
    [2, 3, 4],
    [4, 5, 6],
    [6, 7, 8],
    [8, 9, 0],
    [0, 2, 4],
    [4, 6, 8],
    [8, 0, 2],
    [2, 4, 6],
    [6, 8, 0]])
# Generate all line segments from the triangles
# Repeat each triagle's vertices to form pairs
segments = np.roll(triangles.repeat(2, axis=1), -1, axis=1).reshape(-1,2)
# Sort each segment to ensure consistency (e.g., [0,1] and [1,0] are the same)
segments = np.sort(segments, axis=1)

# Use a structured array to find unique segments
dtype = [('p0', segments.dtype), ('p1', segments.dtype)]
structured_segments = segments.view(dtype)
unique_segments = np.unique(structured_segments)

# Convert back to a regular array
unique_segments = unique_segments.view(segments.dtype).reshape(-1,2)
print(unique_segments)

### 74. Given an array C that is bincount, how to produce an array A such that np.bincount (A) == C?

To produce an array (A) such that np.bincount(A) == C, you can use the np.repeat function

In [ ]:
# Example bincount array
C = np.array([2, 1, 1, 2, 1, 0, 1])
# Generate the array (A)
# np.arange(len(C)) creates an array of integers from 0 to the length of ( C ) minus one.
# np.repeat(np.arange(len(C)), C) repeats each integer in this array according to the corresponding value in ( C )
A = np.repeat(np.arange(len(C)), C)
print(A)

### 75. How to compute averages using a sliding window over an array?

In [ ]:
# Define the array and window size
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3 
# Define a function moving_average that computes the cumulative sum of the array and then calculates the moving average 
    # by subtracting the cumulative sums appropriately and dividing by the window size
def moving_average(a,n):
    # np.cumsum computes the cumulative sum of the array a, and the dtype=float ensures that the result is stored as floating-point numbers
    ret = np.cumsum(a, dtype=float)
    print(f"ret: {ret}")
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:]/n
averages = moving_average(array, window_size)
print(averages)

### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0], Z[1], Z[2]) and each subsequent row is shifted by 1 (last row should be Z[-3], Z[-2], Z[-1])

To build a two-dimensional array from a one-dimensional array (Z), where each row is a shifted version of the previous row, you can use Numpy's `stride_tricks` module.

In [ ]:
def rolling (a, window):
    shape = (a.size - window + 1 , window)
    
    strides = (a.strides[0], a.strides[0])
    # The rolling function uses stride_tricks.as_strided to create a view of the array with the desired shape and strides
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

# Create the one-dimensional array Z
Z = np.arange(10)

# Define the window size
window_size = 3 

# Generate the two-dimensional array
result = rolling(Z, window_size)

print(result)

### 77. How to negate a boolean, or to change the sign of a float inplace?

To change the sign of a float array in place, we can use the `numpy.negative` function or simply multiply the array by -1

In [ ]:
# Example float array
float_array = np.array([1.0, -2.0, 3.0, -4.0])
# Using numpy.negative
np.negative(float_array, out=float_array)
print(float_array)
# Using multiplication by -1
float_array *=-1
print(float_array)

### 78. Consider 2 sets of points P0, P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i], P1[i])

In [ ]:
# Example points 
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
p = np.array([1,2])

# Function to compute distance from point p to each line segment (P0[i], P1[i])
def distance_point_to_lines(P0, P1, p):
    # This computes the vector from each ( P0[i] ) to ( P1[i] )
    line_vec = P1 - P0
    # This computes the vector from each ( P0[i] ) to the point ( p )
    point_vec = p - P0
    # This computes the cross product of the vectors, which gives a measure of the area of the parallelogram formed by the vectors
    cross_prod = np.cross(line_vec, point_vec)
    # This computes the distance from the point to each line by dividing the magnitude of the cross product by the length of the line segment
    distances = np.abs(cross_prod) / np.linalg.norm(line_vec, axis=1)
    return distances 

# Compute distances
distances = distance_point_to_lines(P1, P0, p)
print(distances)
    

### 79. Consider 2 sets of point P0, P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i], P1[i])?

In [ ]:
# Example points
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
P = np.array([[1, 2], [2, 3], [3, 4]])

# Function to compute distance from each point P[j] to each line segment (P0[i], P1[i])
def distance_points_to_lines(P0, P1, P):
    #  This computes the vector from each ( P0[i] ) to ( P1[i] )
    line_vec = P1 -P0
    # Number of lines and points 
    num_lines = P0.shape[0]
    num_points = P.shape[0]
    # Initialize distance matrix
    distances = np.zeros((num_points, num_lines))
    for j in range(num_points):
        # This computes the vector from each ( P0[i] ) to each point ( P[j] )
        point_vec = P[j] - P0 
        # This computes the cross product of the vectors, which gives a measure of the area of the parallelogram formed by the vectors
        cross_prod = np.cross(line_vec, point_vec)
        # This computes the distance from each point to each line by dividing the magnitude of the cross product by the length of the line segment
        distances[j] = np.abs(cross_prod) / np.linalg.norm(line_vec, axis=1)
    return distances 

# Compute distances
distances = distance_points_to_lines(P0, P1, P)
print(distances)

### 80. Consider an arbitray array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

To extract a subarray with a fixed shape centered on a given element and pad with a fill value when necessary, we can use Numpy's `pad` function.

import numpy as np

def extract_subarray_with_padding(arr, center, shape, fill_value=0):
    """
    Extract a subarray of a given shape centered on a specified element, with padding if necessary.
    
    Parameters:
    arr (ndarray): Input array.
    center (tuple): Coordinates of the center element (row, col).
    shape (tuple): Shape of the subarray (height, width).
    fill_value (scalar): Value to use for padding.
    
    Returns:
    subarray (ndarray): Extracted subarray with padding if necessary.
    """
    center_row, center_col = center
    height, width = shape
    half_height, half_width = height // 2, width // 2
    
    # Calculate the start and end indices for slicing
    start_row = center_row - half_height
    end_row = center_row + half_height + (height % 2)
    start_col = center_col - half_width
    end_col = center_col + half_width + (width % 2)
    
    # Pad the array to handle out-of-bounds indices
    padded_arr = np.pad(arr, 
                        ((max(0, -start_row), max(0, end_row - arr.shape[0])),
                         (max(0, -start_col), max(0, end_col - arr.shape[1]))),
                        mode='constant', constant_values=fill_value)
    
    # Adjust indices for the padded array
    start_row_padded = max(0, start_row)
    end_row_padded = start_row_padded + height
    start_col_padded = max(0, start_col)
    end_col_padded = start_col_padded + width
    
    # Extract the subarray
    subarray = padded_arr[start_row_padded:end_row_padded, start_col_padded:end_col_padded]
    
    return subarray

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
center = (1, 1)
shape = (3, 3)
fill_value = 0

subarray = extract_subarray_with_padding(arr, center, shape, fill_value)
print(subarray)


### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] , how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

This code creates the array R by slicing the array Z in a way that each sub-array contains 4 consecutive elements, starting from each element in Z up to the 11th element

In [ ]:
# Step 1: Create the array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
# Step 2: Generate the array R
R = np.array([Z[i:i+4] for i in range(len(Z) - 3)])
print(R)

### 82. Compute a matrix rank

In [ ]:
"""To compute the rank of a matrix using NumPy, you can use the numpy.linalg.matrix_rank function"""
# Step 1: Define the matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# Step 2: Compute the rank
rank = np.linalg.matrix_rank(A)
print("The rank of the matrix is:", rank)

### 83. How to find the most frequent value in an array?

To find the most frequent value in a NumPy array, we can use the numpy.bincount and numpy.argmax functions.  The bincount function counts the occurrences of each value, and argmax returns the index of the highest count, which corresponds to the most frequent value.

In [ ]:
# Step 1: Create the array
array = np.array([1, 2, 3, 4, 1, 2, 1, 1, 3, 4, 4, 4, 4])
# Step 2: Find the most frequent value
counts = np.bincount(array)
most_frequent = np.argmax(counts)
print("The most frequent value is:", most_frequent)

### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

To extract all contiguous 3x3 blocks from a random 10 x 10 matrix using Numpy, you can use the `numpy.lib.stride_trick.as_strided` function. This function allows you to create a view of the array with overlapping blocks. This code will output the original 10x10 matrix and all the contiguous 3x3 blocks extracted from it. The as_strided function is used to create a view of the matrix with the desired block size. 

In [ ]:
# Step 1: Create a random 10x10 matrix
matrix = np.random.randint(0,10, (10,10))

# Step 2: Define the block size
block_size = 3 

# Step 3: Calculate the shape of the resulting array
shape = (matrix.shape[0] - block_size + 1 , matrix.shape[1] - block_size + 1 , block_size, block_size)

# Step 4: Calculate the strides for the resulting array
strides = matrix.strides + matrix.strides

# Step 5: Use as_strided to create the view with 3x3 blocks
blocks = np.lib.stride_tricks.as_strided(matrix, shape=shape, strides=strides)

print("Original 10x10 matrix:\n", matrix)
print("\nContinguous 3x3 blocks: \n", blocks)

### 85. Create a 2D array subclass such that Z[i,j] == Z[i,j]

In [ ]:
 # Define a subclass of numpy.ndarray
class SymmetricArray(np.ndarray):
    # Create a new instance of the subclass
    def __new__(cls, shape, dtype = float, buffer = None, offset =0, strides= None, order= None):
        obj = super(SymmetricArray, cls).__new__(cls, shape, dtype, buffer, offset, strides, order) 
        return obj 

    def __setitem__(self, index, value):
         # Override the __setitem__ method to ensure symmetry
        i, j = index # Unpack the index into row (i) and column (j)
        super(SymmetricArray, self).__setitem__((i,j), value)  # Set the value at (i, j)
        super(SymmetricArray, self).__setitem__((j,i), value) # Set the value at (j, i) to ensure symmetry


# Create a symmetric 2D array with the specified shape
shape = (5,5) # Define the shape of the array
Z = SymmetricArray(shape) # Create an instance of SymmetricArray

# Set some values in the array
Z[0,1] = 10 # Set the value at (0, 1) and (1, 0) to 10
Z[2,3] = 20 # Set the value at (2, 3) and (3, 2) to 20
print(Z)

### 86. Consider a set of p matrices which shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of the p matrix products at once? (result has shape(n,1))

In [57]:
# Example: p = 3 , n = 2
p=3
n=2 

# Initialize p matrices of shape (n,n)
matrices = [np.random.rand(n, n) for _ in range(p)]

# Initialize p vectors of shape (n, 1)
vectors = [np.random.rand(n,1) for _ in range(p)]

# Compute the sum of the matrix products
result = sum(np.dot(matrices[i], vectors[i]) for i in range(p))
print(result)

[[0.92179126]
 [0.79358931]]


C:\Users\men_l\AppData\Local\Temp\ipykernel_26996\1931499033.py:12: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  result = sum(np.dot(matrices[i], vectors[i]) for i in range(p))


### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

To compute the block-sum of a 16x16 array with a block size of 4x4 using Numpy, you can use the `np.add.reduceat` function. This function allows you to sum elements over specified intervals, which is perfect for summoning blocks for an array.

In [61]:
# Create a 16x16 array
array = np.random.rand(16,16)

# Define the block size
block_size = 4

# Compute the block-sum
block_sum = np.add.reduceat(
    # We use np.add.reduceat twice: first to sum the rows in blocks, and then to sum the columns of the resulting array in blocks
    np.add.reduceat(array, np.arange(0, array.shape[0], block_size), axis=0),
    np.arange(0, array.shape[1], block_size), axis=1
)
print(block_sum)

[[6.36753492 8.27730663 7.57709703 6.99771295]
 [7.72905781 8.10280039 7.76357035 8.87023928]
 [8.58392511 6.44363405 8.03525372 5.76073347]
 [6.33958939 6.08730012 6.32704191 6.50393575]]


### 88. How to implement the Game of Life using numpy arrays?

In [68]:
def game_of_life(grid, generations):
    """
    Implements the Game of Life using NumPy arrays.

    Args:
        grid: A 2D NumPy array representing the initial state of the game.
        generations: The number of generations to simulate.

    Returns:
        A 2D NumPy array representing the final state of the game after the specified number of generations.
    """

    rows, cols = grid.shape

    for _ in range(generations):
        # Create a copy of the grid to avoid modifying the current generation while calculating the next
        new_grid = np.copy(grid)

        # Calculate the number of neighbors for each cell
        neighbors = np.zeros_like(grid)
        neighbors[:-1, :] += grid[1:, :]
        neighbors[1:, :] += grid[:-1, :]
        neighbors[:, :-1] += grid[:, 1:]
        neighbors[:, 1:] += grid[:, :-1]
        neighbors[0, :] += grid[-1, :]
        neighbors[-1, :] += grid[0, :]
        neighbors[0, :] += grid[-1, :]
        neighbors[-1, :] += grid[0, :]

        # Apply the Game of Life rules
        new_grid[(neighbors == 3) | (neighbors == 2)] = 1
        new_grid[neighbors != 3] = 0

        # Update the grid for the next generation
        grid = new_grid

    print(grid)

# Example usage
initial_grid = np.random.randint(0, 2, (100, 100))  # Create a random initial grid
final_grid = game_of_life(initial_grid, 100)  # Simulate 100 generations

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]


### 89. How to get n largest values of an array

In [70]:
# Example array
array = np.array([10, 50, 20, 40, 30, 60, 70, 80, 90, 100])

# Number of largest values to find
n = 3 

# np.argpartition(array, -n) partitions the array such that the ( n ) largest values are at the end
indices = np.argpartition(array, -n)[-n:]

# array[indices] retrieves the actual values from the array
n_largest_values = array[indices]

# np.sort(n_largest_values)[::-1] sorts the ( n ) largest values in descending order
n_largest_values_sorted = np.sort(n_largest_values)[::-1]

print(f"n_largest_values_sorted :\n {n_largest_values_sorted }")

n_largest_values_sorted :
 [100  90  80]
