
#### Numpy enables fast computation in Python, the underlying implementation is in C hence it's blazing fast. They key feature of Numpy is the ndarray object. The data type should be homogenous, that is the array should contain elements of single data type


In [10]:
import numpy as np

In [5]:
vector = np.array([1,2,3,4])
print("vector: {}".format(vector))
# Every array will have a shape. That is, its dimensions
print("Shape: {}".format(vector.shape))
# Print number of dimensions
print("Dim: {}".format(vector.ndim))
print("Data type: {}".format(vector.dtype))


vector: [1 2 3 4]
Shape: (4,)
Dim: 1
Data type: int32


## Creating Arrays

### Zeros and Ones

* **`zeros(dim)`:** Returns a NumPy array of dimension `dim` initialized with zeros. 
    * **Example:** `zeros((3, 4))` creates a 3x4 array of zeros.
* **`ones(dim)`:** Similar to `zeros`, but initializes with ones.

### Empty Arrays
* **`empty(dim)`:** Creates an uninitialized NumPy array of dimension `dim`. 
    * **Note:** Values in an empty array are arbitrary and may contain garbage data.



In [7]:
v = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
v.shape = (2,3,2)
print(v)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
v = np.zeros((2,3,3))
print(v)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### arange

#### The arrange function is similar to Python's range function. The data type, if not specified, in many cases will be np.float64

In [11]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]



### `zeros` and `zeros_like`

#### `zeros(dim)`
Returns a `np.array` of dimension `dim` initialized with 0. Note that `dim` should be a tuple.

### `ones` and `ones_like`
Provides the same functionality as `zeros` and `zeros_like`, except the initialization is done with ones.

### `empty` and `empty_like`
Creates NumPy arrays but doesn't initialize them with any values (hence, faster). By default, all the values in the array will have garbagto let me know!