
#### Numpy enables fast computation in Python, the underlying implementation is in C hence it's blazing fast. They key feature of Numpy is the ndarray object. The data type should be homogenous, that is the array should contain elements of single data type


In [2]:
import numpy as np

In [3]:
vector = np.array([1,2,3,4])
print("vector: {}".format(vector))
# Every array will have a shape. That is, its dimensions
print("Shape: {}".format(vector.shape))
# Print number of dimensions
print("Dim: {}".format(vector.ndim))
print("Data type: {}".format(vector.dtype))


vector: [1 2 3 4]
Shape: (4,)
Dim: 1
Data type: int32


## Creating Arrays

### Zeros and Ones

* **`zeros(dim)`:** Returns a NumPy array of dimension `dim` initialized with zeros. 
    * **Example:** `zeros((3, 4))` creates a 3x4 array of zeros.
* **`ones(dim)`:** Similar to `zeros`, but initializes with ones.

### Empty Arrays
* **`empty(dim)`:** Creates an uninitialized NumPy array of dimension `dim`. 
    * **Note:** Values in an empty array are arbitrary and may contain garbage data.



In [4]:
v = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
v.shape = (2,3,2)
print(v)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
v = np.zeros((2,3,3))
print(v)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### arange

#### The arrange function is similar to Python's range function. The data type, if not specified, in many cases will be np.float64

In [6]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]



### `zeros` and `zeros_like`

#### `zeros(dim)`
Returns a `np.array` of dimension `dim` initialized with 0. Note that `dim` should be a tuple.

### `ones` and `ones_like`
Provides the same functionality as `zeros` and `zeros_like`, except the initialization is done with ones.

### `empty` and `empty_like`
Creates NumPy arrays but doesn't initialize them with any values (hence, faster). By default, all the values in the array will have garbagto let me know!

In [7]:
print("Zeros")
# Creates a 3x3 array filled with zeros.
a = np.zeros((3,3))
print("A: {}".format(a))
# Creates a new array with the same shape and data type as the existing array a
b = np.zeros_like(a)
print("B: {}".format(b))
print("\nOnes")
# Creates a 3x3 array filled with ones
a = np.ones((3,3))
print("A: {}".format(a))
# Creates a new array with the same shape and data type as the existing array a
b= np.ones_like(a)
print("B: {}".format(b))
print("\nEmpty")
# Creates a 3x3 array with uninitialized values. The values will be whatever happens to be in memory at that location
a = np.empty((3,3))
print("A: {}".format(a))
'''As you can see, the zeros and ones arrays are initialized with their respective values, 
while the empty array's initial values are arbitrary and depend on the memory state'''


Zeros
A: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
B: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones
A: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Empty
A: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


"As you can see, the zeros and ones arrays are initialized with their respective values, \nwhile the empty array's initial values are arbitrary and depend on the memory state"

## `astype`

**`astype`** is used to convert the data type of a NumPy array. It creates a new copy of the array, even if the data type remains the same.

**Note:** Converting from a higher-precision data type to a lower-precision data type can result in loss of information. For example, converting a float to an integer will truncate the decimal part.



In [8]:
a = np.array([1, 2, 3, 4.5, 6.7]) ## Create a NumPy array with mixed integer and float values
print("A: {}, dtype: {}".format(a, a.dtype))
b = a.astype(int)  # Convert the array 'a' to integer data type, truncating decimal parts
print("B: {}, dtype: {}".format(b, b.dtype))

A: [1.  2.  3.  4.5 6.7], dtype: float64
B: [1 2 3 4 6], dtype: int32


## Vectorization and Vector-Scalar Operations

Using for loops in code is not only prone to error but also inefficient. We can use NumPy operations to circumvent such for loops. This process is called vectorization.

### Using operation on same sized arrays produce element wise operations.

In [9]:
# Creates a 2x3 NumPy array named a with the given values
a = np.array([[1,2,3], [4,5,6]])
# Creates another 2x3 NumPy array named b with the given values
b = np.array([[4,5,6], [1,2,3]])

# Performs element-wise addition of a and b, storing the result in c
c = a + b
print(c)

# Performs element-wise multiplication of a and b, storing the result in c
c = a * b 
print(c)

# Performs element-wise subtraction of b from a, storing the result in c
c = a-b 
print(c)

[[5 7 9]
 [5 7 9]]
[[ 4 10 18]
 [ 4 10 18]]
[[-3 -3 -3]
 [ 3  3  3]]


#### Using scalars with vectors will produce element wise operations

In [10]:
# Creates a scalar variable a and assigns it the value 3
a = 3 
# Creates a 2x3 NumPy array named b with the given values
b = np.array([[1,2,3], [4,5,6]])

# Attempts to add the scalar a to each element of the array b. 
# NumPy automatically broadcasts the scalar a to match the shape of b, resulting in element-wise addition.
c = a + b 
print(c)

# Attempts to multiply the scalar a with each element of the array b.
# NumPy automatically broadcasts the scalar a to match the shape of b, resulting in element-wise multiplication
c = a * b 
print(c)

# Performs element-wise division of 1.0 by each element of the array b. 
# This results in a new array c where each element is the reciprocal of the corresponding element in b
c = 1.0/b
print(c)

[[4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


### Slicing 
You can slice by following syntax:
>array[start_index:end_index]

For n_dimension array:

>array[start_index:index_index, start_index:end_index]

Slicing Numpy arrays is similar to that of Python lists. One main distinction in Python list and Numpy array **is not the copy, but the original array. Hence, if any operations on the slice will be reflected in the original array.**

In [11]:
a = np.arange(20)
print(a)
a[10:15] = 5 #Modifies elements 10 to 14 (inclusive) of the array a to the value 5
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9  5  5  5  5  5 15 16 17 18 19]


If you want to avoid the above scenario, you can use `copy()`

In [12]:
a = np.arange(20)
print(a)
# Creates a copy of elements 10 to 14 (inclusive) of the array a and stores it in the variable b. 
# This means that b is a separate object in memory, independent of a
b  = a[10:15].copy()
# Assigns the value 5 to all elements of the array b. Since b is a copy, this change does not affect the original array a
b = 5 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]



Slicing by `:` will take the entire axis. So:
>1. `arr2d[:, 0]` will return an array of shape (3, )
>2. `arr2d[:, :1]` will return an array of shape (3, 1)

In [13]:
# This line creates a 2D NumPy array named arr2d. The array contains three rows and three columns of numerical data
arr2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
# arr2d[:, 0]: This line extracts the first column from the arr2d array. Here's a breakdown of the slicing notation:
#: This colon represents all elements in the specified dimension. In this case, it means selecting all rows.
#0: This integer specifies the index of the column to be selected. So, 0 indicates the first column
arr2d[:,0]

array([1, 4, 7])

# Boolean ndexing 
Using boolean indexing, you can use it to filter or check if any entries have any specific values.

In [16]:
# This line creates a NumPy array named a containing a list of strings
a= np.array(["Mayur", "is", "an", "awesome", "coder"])

# This line performs an element-wise comparison between each element in the a array and the string "Mayur". 
# The comparison operator == checks if each element is equal to "Mayur"
a == "Mayur" #Return boolean array

array([ True, False, False, False, False])

In [20]:
# List entry where value != "Mayur"
# This expression first performs the element-wise comparison between each element in the array and the string "Mayur" 
# The ~ operator then negates the resulting boolean array.
# This means that elements that were previously True (equal to "Mayur") will now be False, and vice versa
a[~(a=="Mayur")]

array(['is', 'an', 'awesome', 'coder'], dtype='<U7')

You can use `|` for `or` and `&` for `and` but not Python's `and`, `or` will not work in Numpy's indexing.

In [28]:
# This expression combines the results of the two previous comparisons using the bitwise OR operator (|).
# It performs an element-wise logical OR operation on the two boolean arrays. 
# The result is a new boolean array where True indicates elements that are either equal to "Mayur" or "coder", 
# and False indicates elements that are neither

(a=="Mayur") | (a=='coder')


array([ True, False, False, False,  True])

## Fancy indexing
You can index a list to print the array in the given order. For instance, you want to print the 1st row, 3rd row, and 2nd row in that order.

In [31]:
# This line creates a 2D NumPy array named a containing four rows and three columns of numerical data
a = np.array([[1,1,1], [2,2,2], [3,3,3], [4,4,4]])
print(a)
# This line extracts specific rows from the a array using integer indexing. 
# The expression [1, 3, 2] specifies the indices of the rows to be selected. 
# In this case, it will return the second, fourth, and third rows of the array in that order
a[[1,3,2]]

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


array([[2, 2, 2],
       [4, 4, 4],
       [3, 3, 3]])

## Tranposing 
You can obtain the transpose of your matring using `matrix. T` where `matrix` is your matrix name. 

In [32]:
# This line creates a 2D NumPy array named a containing four rows and three columns of numerical data
a = np.array([[1,1,1], [2,2,2], [3,3,3], [4,4,4]])
# This line transposes the a array. Transposition means swapping the rows and columns of the array.
# In other words, it converts the original array from a 4x3 matrix to a 3x4 matrix
print(a.T)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
